Repository modelscope/data-juicer, pull requests merged in 2023-11, with the labels that each got.

#51 Feat/add chinese mapper
  configs/config_all.yaml
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/chinese_convert_mapper.py
  data_juicer/ops/mapper/remove_non_chinese_character_mapper.py
  demos/overview_scan/app.py
  docs/Operators.md
  docs/Operators_ZH.md
  environments/science_requires.txt
  tests/ops/mapper/test_chinese_convert_mapper.py
  tests/ops/mapper/test_remove_non_chinese_character_mapper.py
Labels: enhancement

#54 docs: update model links on huggingface and modelscope
  README.md
  README_ZH.md
Labels: documentation, enhancement

#64 Dev/multimodal format & basic processing pipeline for multimodal datasets support
  configs/config_all.yaml
  data_juicer/config/config.py
  data_juicer/core/analyser.py
  data_juicer/core/executor.py
  data_juicer/core/exporter.py
  data_juicer/format/formatter.py
  data_juicer/format/mixture_formatter.py
  data_juicer/format/text_formatter.py
  data_juicer/ops/base_op.py
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/image_aspect_ratio_filter.py
  data_juicer/ops/op_fusion.py
  data_juicer/utils/constant.py
  data_juicer/utils/mm_utils.py
  demos/overview_scan/app.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/config/demo_4_test.yaml
  tests/config/test_config_funcs.py
  tests/ops/data/img1.png
  tests/ops/data/img2.jpg
  tests/ops/data/img3.jpg
  tests/ops/filter/test_image_aspect_ratio_filter.py
  tools/multimodal/README.md
  tools/multimodal/README_ZH.md
  tools/multimodal/data_juicer_format_to_target_format/dj_to_llava.py
  tools/multimodal/source_format_to_data_juicer_format/llava_to_dj.py
Labels: enhancement, dj:multimodal

#68 * fix pre-commit failures and add pre-commit action
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  data_juicer/config/config.py
  data_juicer/core/exporter.py
  data_juicer/core/ray_executor.py
  data_juicer/format/formatter.py
  data_juicer/format/text_formatter.py
  data_juicer/ops/base_op.py
  data_juicer/ops/filter/character_repetition_filter.py
  data_juicer/ops/filter/image_aspect_ratio_filter.py
  data_juicer/ops/filter/language_id_score_filter.py
  data_juicer/ops/filter/special_characters_filter.py
  data_juicer/ops/filter/word_repetition_filter.py
  data_juicer/ops/mapper/punctuation_normalization_mapper.py
  data_juicer/ops/mapper/remove_comments_mapper.py
  data_juicer/utils/mm_utils.py
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  tools/converter/convert_gpt_to_transformers.py
  tools/converter/modeling_megatron_llama.py
  tools/evaluator/evaluator.py
  tools/evaluator/gpt_eval/answer_generator.py
  tools/evaluator/gpt_eval/gpt_evaluator.py
  tools/evaluator/recorder/wandb_writer.py
  tools/hpo/execute_hpo.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_llava.py
  tools/multimodal/source_format_to_data_juicer_format/llava_to_dj.py
  tools/preprocess/serialize_meta.py
Labels: enhancement

#73 added image_size_filter
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/image_size_filter.py
  data_juicer/utils/constant.py
  data_juicer/utils/mm_utils.py
  demos/overview_scan/app.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/filter/test_image_size_filter.py
Labels: enhancement, dj:multimodal

#69 Feature/clip similarity filter
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/clip_similarity_filter.py
  data_juicer/utils/constant.py
  data_juicer/utils/model_utils.py
  demos/overview_scan/app.py
  docs/Operators.md
  docs/Operators_ZH.md
  environments/science_requires.txt
  tests/ops/data/cat.jpg
  tests/ops/filter/test_clip_similarity_filter.py
Labels: enhancement, dj:multimodal

#72 add image_deduplicator
  configs/config_all.yaml
  data_juicer/ops/deduplicator/__init__.py
  data_juicer/ops/deduplicator/image_deduplicator.py
  data_juicer/utils/constant.py
  demos/overview_scan/app.py
  docs/Operators.md
  docs/Operators_ZH.md
  environments/science_requires.txt
  tests/ops/data/img4.png
  tests/ops/data/img5.jpg
  tests/ops/data/img6.jpg
  tests/ops/data/img7.jpg
  tests/ops/deduplicator/test_image_deduplicator.py
  tests/ops/filter/test_image_aspect_ratio_filter.py
Labels: enhancement, dj:multimodal

#74 Feature/image shape filter
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/image_shape_filter.py
  data_juicer/utils/compress.py
  data_juicer/utils/constant.py
  demos/overview_scan/app.py
  docs/Operators.md
  docs/Operators_ZH.md
  environments/minimal_requires.txt
  tests/ops/filter/test_image_shape_filter.py
Labels: enhancement, dj:multimodal

#76 * fix bug in nlpaug_en_mapper: nlpaug could generate an indefinite numbers of augmented samples
  data_juicer/ops/mapper/nlpaug_en_mapper.py
  data_juicer/ops/mapper/nlpcda_zh_mapper.py
Labels: bug

#78 sytle: read op description from markdown
  demos/overview_scan/app.py
Labels: documentation, enhancement

#77 added acknowledgement in homepage
  README.md
  README_ZH.md
  thirdparty/README.md
Labels: documentation

#79 * opt: convert relative paths only when it's necessary
  data_juicer/format/formatter.py
Labels: enhancement, dj:multimodal

#83 fix opencc serialization error
  data_juicer/ops/mapper/chinese_convert_mapper.py
Labels: bug

#82 * Add availability checking for OPs to allow incomplete dependency installation
  README.md
  README_ZH.md
  data_juicer/core/ray_executor.py
  data_juicer/ops/deduplicator/document_minhash_deduplicator.py
  data_juicer/ops/deduplicator/document_simhash_deduplicator.py
  data_juicer/ops/deduplicator/image_deduplicator.py
  data_juicer/ops/filter/alphanumeric_filter.py
  data_juicer/ops/filter/clip_similarity_filter.py
  data_juicer/ops/filter/flagged_words_filter.py
  data_juicer/ops/filter/language_id_score_filter.py
  data_juicer/ops/filter/perplexity_filter.py
  data_juicer/ops/filter/stopwords_filter.py
  data_juicer/ops/filter/token_num_filter.py
  data_juicer/ops/filter/word_num_filter.py
  data_juicer/ops/filter/word_repetition_filter.py
  data_juicer/ops/load.py
  data_juicer/ops/mapper/chinese_convert_mapper.py
  data_juicer/ops/mapper/clean_html_mapper.py
  data_juicer/ops/mapper/fix_unicode_mapper.py
  data_juicer/ops/mapper/nlpaug_en_mapper.py
  data_juicer/ops/mapper/nlpcda_zh_mapper.py
  data_juicer/ops/mapper/remove_words_with_incorrect_substrings_mapper.py
  data_juicer/ops/mapper/sentence_split_mapper.py
  data_juicer/utils/availability_utils.py
  environments/dist_requires.txt
  environments/minimal_requires.txt
  environments/science_requires.txt
  setup.py
Labels: enhancement

#94 * bug fixed: serialize simhash failed.
  data_juicer/ops/deduplicator/document_simhash_deduplicator.py
Labels: bug

#95 support audio & audio-text data reading
  configs/config_all.yaml
  data_juicer/utils/mm_utils.py
  tools/multimodal/README.md
  tools/multimodal/README_ZH.md
  tools/multimodal/data_juicer_format_to_target_format/dj_to_llava.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_wavcaps.py
  tools/multimodal/source_format_to_data_juicer_format/wavcaps_to_dj.py
Labels: enhancement, dj:multimodal

#99 fix: remove extra prepare model when enable tokenization flag in some ops.
  data_juicer/utils/model_utils.py
Labels: bug

#91 Enhance/mmc4 converting tools
  tools/multimodal/README.md
  tools/multimodal/README_ZH.md
  tools/multimodal/data_juicer_format_to_target_format/dj_to_llava.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_mmc4.py
  tools/multimodal/source_format_to_data_juicer_format/llava_to_dj.py
  tools/multimodal/source_format_to_data_juicer_format/mmc4_to_dj.py
Labels: enhancement, dj:multimodal

#106 Better Analyzer support for stats of multimodal OPs & other minor enhancements
  data_juicer/analysis/column_wise_analysis.py
  data_juicer/analysis/overall_analysis.py
  data_juicer/config/config.py
  data_juicer/core/analyser.py
  data_juicer/core/data.py
  data_juicer/core/executor.py
  data_juicer/core/exporter.py
  data_juicer/format/formatter.py
  data_juicer/format/text_formatter.py
  data_juicer/ops/load.py
  demos/tool_dataset_splitting_by_language/dataset_splitting_by_language.py
  tools/preprocess/dataset_split_by_language.py
Labels: enhancement, dj:multimodal
