Repository modelscope/data-juicer, pull requests merged in 2023-12, with the labels that each got.

#100 Feature/image text matching
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/image_text_matching_filter.py
  data_juicer/ops/filter/image_text_similarity_filter.py
  data_juicer/utils/constant.py
  data_juicer/utils/mm_utils.py
  data_juicer/utils/model_utils.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/data/blip.jpg
  tests/ops/filter/test_image_text_matching_filter.py
  tests/ops/filter/test_image_text_similarity_filter.py
Labels: enhancement, dj:multimodal

#110 Feature/face_area_filter
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/face_area_filter.py
  data_juicer/utils/constant.py
  data_juicer/utils/mm_utils.py
  docs/Operators.md
  docs/Operators_ZH.md
  environments/science_requires.txt
  tests/ops/data/lena-face.jpg
  tests/ops/data/lena.jpg
  tests/ops/filter/test_face_area_filter.py
Labels: enhancement, dj:multimodal

#122 Two addition filter for image captions (resubmit)
  .pre-commit-config.yaml
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/text_action_filter.py
  data_juicer/ops/filter/text_entity_dependency_filter.py
  data_juicer/utils/constant.py
  docs/Operators.md
  docs/Operators_ZH.md
  environments/science_requires.txt
  tests/ops/filter/test_text_action_filter.py
  tests/ops/filter/test_text_entity_dependency_filter.py
Labels: enhancement

#121 + add documents about OP docs update and fusible OP development.
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
Labels: documentation

#137 fix: 1. change relpath to abspath of dataset
  data_juicer/config/config.py
  data_juicer/utils/availability_utils.py
  data_juicer/utils/fingerprint_utils.py
Labels: enhancement

#140 add an auto-hpo tool for data-recipes based on 3-sigma rule
  data_juicer/analysis/column_wise_analysis.py
  data_juicer/analysis/overall_analysis.py
  data_juicer/config/config.py
  data_juicer/core/analyser.py
  data_juicer/utils/constant.py
  tools/hpo/README.md
  tools/hpo/README_ZH.md
  tools/hpo/execute_hpo_3sigma.py
  tools/hpo/execute_hpo_wandb.py
Labels: enhancement

#142 docs: fix broken link
  README_ZH.md
Labels: documentation

#147 bugfix for un-aligned types (int v.s. float) caused by two OPs
  data_juicer/config/config.py
  data_juicer/ops/filter/maximum_line_length_filter.py
Labels: bug

#151 Enhance/several minor opts
  data_juicer/config/config.py
  data_juicer/ops/filter/language_id_score_filter.py
  tests/ops/filter/test_language_id_score_filter.py
Labels: bug, enhancement

#157 * bug fixed: missing attribute dataset_dir when the input dataset path is remote or a mixture of several datasets.
  data_juicer/config/config.py
  data_juicer/format/formatter.py
Labels: bug

#149 add remove_repeat_sentences_mapper
  configs/config_all.yaml
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/remove_repeat_sentences_mapper.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/mapper/test_remove_repeat_sentences_mapper.py
Labels: enhancement
