Repository modelscope/data-juicer, pull requests merged in 2024-07, with the labels that each got.

#352 add paper list according to https://arxiv.org/abs/2407.08583
  docs/awesome_llm_data.md
Labels: documentation

#351 Fix several bugs for image OPs
  configs/config_all.yaml
  data_juicer/__init__.py
  data_juicer/ops/deduplicator/image_deduplicator.py
  data_juicer/ops/deduplicator/video_deduplicator.py
  data_juicer/utils/model_utils.py
  tests/ops/deduplicator/test_image_deduplicator.py
  tests/ops/deduplicator/test_video_deduplicator.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_llava.py
Labels: bug, enhancement

#355 change CH mark to EN mark
  README.md
  README_ZH.md
  docs/Operators.md
  docs/Operators_ZH.md
Labels: documentation

#332 Dev/rebuild sandbox
  README.md
  README_ZH.md
  app.py
  configs/README.md
  configs/config_all.yaml
  configs/demo/analyser.yaml
  configs/demo/process.yaml
  configs/demo/sandbox/gpt3_data_quality_eval_config.yaml
  configs/demo/sandbox/gpt3_extra_train_config.json
  configs/demo/sandbox/gpt3_extra_train_config.yaml
  configs/demo/sandbox/sandbox.yaml
  data_juicer/analysis/column_wise_analysis.py
  data_juicer/analysis/diversity_analysis.py
  data_juicer/analysis/overall_analysis.py
  data_juicer/config/__init__.py
  data_juicer/config/config.py
  data_juicer/core/__init__.py
  data_juicer/core/analyzer.py
  data_juicer/core/sandbox/hooks.py
  data_juicer/core/sandbox/pipelines.py
  data_juicer/utils/constant.py
  demos/data_mixture/data/the-pile-nih-refined.jsonl
  demos/data_process_loop/app.py
  demos/data_visualization_diversity/app.py
  demos/data_visualization_op_effect/app.py
  demos/data_visualization_statistics/app.py
  demos/overview_scan/app.py
  demos/process_cft_zh_data/app.py
  demos/process_code_data/app.py
  demos/process_sci_data/app.py
  demos/process_sci_data/data/arxiv.jsonl
  docs/Sandbox-ZH.md
  docs/Sandbox.md
  tools/analyze_data.py
  tools/hpo/execute_hpo_3sigma.py
  tools/sandbox_starter.py
Labels: documentation, enhancement

#354 Enhance GPU Management, Operator Control, and Multiprocessing
  data_juicer/__init__.py
  data_juicer/core/analyzer.py
  data_juicer/core/executor.py
  data_juicer/core/ray_executor.py
  data_juicer/ops/__init__.py
  data_juicer/ops/base_op.py
  data_juicer/ops/filter/image_aesthetics_filter.py
  data_juicer/ops/filter/image_nsfw_filter.py
  data_juicer/ops/filter/image_text_matching_filter.py
  data_juicer/ops/filter/image_text_similarity_filter.py
  data_juicer/ops/filter/image_watermark_filter.py
  data_juicer/ops/filter/phrase_grounding_recall_filter.py
  data_juicer/ops/filter/video_aesthetics_filter.py
  data_juicer/ops/filter/video_frames_text_similarity_filter.py
  data_juicer/ops/filter/video_motion_score_filter.py
  data_juicer/ops/filter/video_nsfw_filter.py
  data_juicer/ops/filter/video_ocr_area_ratio_filter.py
  data_juicer/ops/filter/video_tagging_from_frames_filter.py
  data_juicer/ops/filter/video_watermark_filter.py
  data_juicer/ops/mapper/extract_qa_mapper.py
  data_juicer/ops/mapper/image_captioning_mapper.py
  data_juicer/ops/mapper/image_diffusion_mapper.py
  data_juicer/ops/mapper/video_captioning_from_audio_mapper.py
  data_juicer/ops/mapper/video_captioning_from_frames_mapper.py
  data_juicer/ops/mapper/video_captioning_from_summarizer_mapper.py
  data_juicer/ops/mapper/video_captioning_from_video_mapper.py
  data_juicer/ops/mapper/video_tagging_from_audio_mapper.py
  data_juicer/ops/mapper/video_tagging_from_frames_mapper.py
  data_juicer/ops/op_fusion.py
  data_juicer/utils/model_utils.py
  data_juicer/utils/process_utils.py
  data_juicer/utils/unittest_utils.py
  tests/config/test_config_funcs.py
Labels: bug, enhancement

#358 sandbox_news
  README.md
  README_ZH.md
  docs/Sandbox-ZH.md
  docs/Sandbox.md
Labels: documentation

#365 correct num_proc logic
  data_juicer/config/config.py
  data_juicer/core/ray_data.py
  data_juicer/ops/filter/video_ocr_area_ratio_filter.py
  data_juicer/utils/process_utils.py
  tests/config/test_config_funcs.py
Labels: bug, priority:high

#366 update docs according to recently refactor and events
  README.md
  README_ZH.md
  docs/DJ_SORA.md
  docs/DJ_SORA_ZH.md
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  docs/Operators.md
  docs/Operators_ZH.md
  docs/awesome_llm_data.md
Labels: documentation

#367 minor typo fix and improve "back_to_index" in dj homepage
  README.md
  README_ZH.md
Labels: documentation

#361 feat: Enhance video_motion_score_filter capabilities
  configs/config_all.yaml
  data_juicer/ops/filter/video_motion_score_filter.py
  data_juicer/utils/unittest_utils.py
  tests/ops/filter/test_video_motion_score_filter.py
Labels: enhancement, dj:multimodal, dj:op
