Repository modelscope/data-juicer, pull requests merged in 2024-05, with the labels that each got.

#302 bugfix for the type hints checking when args were specified in yaml file
  data_juicer/config/config.py
  data_juicer/utils/logger_utils.py
  tests/config/demo_4_test_bad_val.yaml
  tests/config/test_config_funcs.py
Labels: bug

#309 Stats saving path option for filter op
  data_juicer/core/executor.py
  data_juicer/core/exporter.py
  data_juicer/core/ray_executor.py
  data_juicer/ops/base_op.py
  tests/config/test_config_funcs.py
Labels: enhancement

#310 Minor update the github io page, for KDD'24 tutorial placeholder
  docs/sphinx_doc/README.md
  docs/sphinx_doc/README_ZH.md
  docs/sphinx_doc/source/_static/tutorial_kdd24.html
  docs/sphinx_doc/source/conf.py
  docs/sphinx_doc/source/index.rst
Labels: documentation, dj:multimodal

#273 Dev/fvd eval
  .pre-commit-config.yaml
  configs/demo/sandbox/inception_eval_config.yaml
  data_juicer/core/sandbox/evaluators.py
  data_juicer/core/sandbox/factories.py
  docs/Sandbox-ZH.md
  docs/Sandbox.md
  tools/mm_eval/__init__.py
  tools/mm_eval/inception_metrics/README.md
  tools/mm_eval/inception_metrics/README_ZH.md
  tools/mm_eval/inception_metrics/calc_metrics_for_videos.py
  tools/mm_eval/inception_metrics/dataset.py
  tools/mm_eval/inception_metrics/distributed.py
  tools/mm_eval/inception_metrics/util.py
  tools/mm_eval/inception_metrics/video_metrics/frechet_inception_distance.py
  tools/mm_eval/inception_metrics/video_metrics/frechet_video_distance.py
  tools/mm_eval/inception_metrics/video_metrics/inception_score.py
  tools/mm_eval/inception_metrics/video_metrics/kernel_inception_distance.py
  tools/mm_eval/inception_metrics/video_metrics/kernel_video_distance.py
  tools/mm_eval/inception_metrics/video_metrics/metric_main.py
  tools/mm_eval/inception_metrics/video_metrics/metric_utils.py
  tools/mm_eval/inception_metrics/video_metrics/precision_recall.py
  tools/mm_eval/inception_metrics/video_metrics/video_inception_score.py
  tools/mm_eval/inception_metrics/video_metrics/video_precision_recall.py
Labels: documentation, enhancement, dj:multimodal

#312 Eval/vbench
  .github/workflows/unit-test.yml
  Dockerfile
  README.md
  README_ZH.md
  configs/demo/sandbox/vbench_eval_config.yaml
  data_juicer/core/sandbox/evaluators.py
  data_juicer/core/sandbox/factories.py
  docs/Sandbox-ZH.md
  docs/Sandbox.md
  environments/sandbox_requires.txt
  environments/science_requires.txt
  setup.py
  tools/mm_eval/README.md
  tools/mm_eval/README_ZH.md
  tools/mm_eval/vbench_metrics/VBench_full_info.json
  tools/mm_eval/vbench_metrics/evaluate.py
Labels: documentation, enhancement, dj:multimodal

#313 Feat/analyzer enhance & multimodal + text duduplication
  configs/config_all.yaml
  data_juicer/config/config.py
  data_juicer/core/analyser.py
  data_juicer/core/exporter.py
  data_juicer/ops/deduplicator/image_deduplicator.py
  data_juicer/ops/deduplicator/video_deduplicator.py
  tests/ops/deduplicator/test_image_deduplicator.py
  tests/ops/deduplicator/test_video_deduplicator.py
Labels: enhancement, dj:op

#318 Dev/fix video filter for bench
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/image_nsfw_filter.py
  data_juicer/ops/filter/image_watermark_filter.py
  data_juicer/ops/filter/video_aspect_ratio_filter.py
  data_juicer/ops/filter/video_nsfw_filter.py
  data_juicer/ops/filter/video_watermark_filter.py
  data_juicer/ops/filter/words_num_filter.py
  docs/BadDataExhibition.md
  docs/BadDataExhibition_ZH.md
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/filter/test_token_num_filter.py
  tests/ops/filter/test_word_num_filter.py
Labels: bug, dj:op
