Repository modelscope/data-juicer, pull requests merged in 2024-12, with the labels that each got.

#503 Quick fix for some minor problems
  .github/workflows/unit-test.yml
  data_juicer/utils/mm_utils.py
  tests/ops/filter/test_audio_duration_filter.py
  tests/ops/filter/test_audio_nmf_snr_filter.py
  tests/ops/filter/test_video_motion_score_raft_filter.py
  tests/ops/filter/test_video_tagging_from_frames_filter.py
  tests/ops/mapper/test_video_tagging_from_audio_mapper.py
Labels: bug, dj:multimodal

#504 fix batch bug
  data_juicer/core/data.py
  data_juicer/ops/base_op.py
  environments/minimal_requires.txt
Labels: bug

#483 Performance benchmark
  .github/workflows/perf-bench.yml
  configs/config_all.yaml
  data_juicer/config/config.py
  data_juicer/core/data.py
  data_juicer/core/executor.py
  data_juicer/core/monitor.py
  data_juicer/utils/model_utils.py
  docs/Operators_ZH.md
  environments/dev_requires.txt
  environments/science_requires.txt
  tests/benchmark_performance/configs/audio.yaml
  tests/benchmark_performance/configs/image.yaml
  tests/benchmark_performance/configs/text.yaml
  tests/benchmark_performance/configs/video.yaml
  tests/benchmark_performance/report.py
  tests/benchmark_performance/run.sh
Labels: enhancement

#506 Patch for Perf Bench
  .github/workflows/deploy_sphinx_docs.yml
  .github/workflows/perf-bench.yml
  configs/config_all.yaml
  environments/minimal_requires.txt
  tests/benchmark_performance/configs/video.yaml
  tests/benchmark_performance/run.sh
  tests/ops/filter/test_audio_duration_filter.py
  tests/ops/filter/test_audio_nmf_snr_filter.py
  tests/ops/mapper/test_video_tagging_from_audio_mapper.py
Labels: enhancement

#508 install by recipe
  README.md
  README_ZH.md
  data_juicer/utils/auto_install_mapping.py
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  setup.py
  tools/dj_install.py
Labels: enhancement

#515 DJ Ray mode supports streaming loading of `jsonl` files
  data_juicer/core/ray_data.py
  data_juicer/core/ray_executor.py
Labels: dj:dataset, dj:efficiency

#512 [Feature] add auto mode for analyzer
  README.md
  README_ZH.md
  configs/config_all.yaml
  data_juicer/analysis/column_wise_analysis.py
  data_juicer/config/config.py
  data_juicer/core/analyzer.py
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/image_aesthetics_filter.py
  data_juicer/ops/filter/image_nsfw_filter.py
  data_juicer/ops/filter/image_text_matching_filter.py
  data_juicer/ops/filter/image_text_similarity_filter.py
  data_juicer/ops/filter/image_watermark_filter.py
  data_juicer/ops/filter/phrase_grounding_recall_filter.py
  data_juicer/ops/filter/video_aesthetics_filter.py
  data_juicer/ops/filter/video_frames_text_similarity_filter.py
  data_juicer/ops/filter/video_nsfw_filter.py
  data_juicer/ops/filter/video_tagging_from_frames_filter.py
  data_juicer/ops/filter/video_watermark_filter.py
  data_juicer/ops/mapper/image_captioning_mapper.py
  data_juicer/ops/mapper/image_diffusion_mapper.py
  data_juicer/ops/mapper/image_tagging_mapper.py
  data_juicer/ops/mapper/video_captioning_from_audio_mapper.py
  data_juicer/ops/mapper/video_captioning_from_frames_mapper.py
  data_juicer/ops/mapper/video_captioning_from_summarizer_mapper.py
  data_juicer/ops/mapper/video_captioning_from_video_mapper.py
  data_juicer/ops/mapper/video_tagging_from_audio_mapper.py
  data_juicer/ops/mapper/video_tagging_from_frames_mapper.py
  environments/dev_requires.txt
  environments/minimal_requires.txt
  environments/sandbox_requires.txt
Labels: enhancement, dj:core

#516 [Feat] OP-wise Insight Mining
  README.md
  README_ZH.md
  data_juicer/analysis/column_wise_analysis.py
  data_juicer/analysis/measure.py
  data_juicer/analysis/overall_analysis.py
  data_juicer/config/config.py
  data_juicer/core/adapter.py
  data_juicer/core/analyzer.py
  data_juicer/core/data.py
  data_juicer/core/executor.py
  data_juicer/core/exporter.py
  data_juicer/core/monitor.py
  data_juicer/ops/__init__.py
  data_juicer/ops/base_op.py
  data_juicer/ops/filter/specified_field_filter.py
  data_juicer/ops/filter/specified_numeric_field_filter.py
  data_juicer/ops/filter/suffix_filter.py
  data_juicer/ops/filter/video_tagging_from_frames_filter.py
  data_juicer/ops/mapper/image_tagging_mapper.py
  data_juicer/ops/mapper/video_tagging_from_audio_mapper.py
  data_juicer/ops/mapper/video_tagging_from_frames_mapper.py
  data_juicer/utils/cache_utils.py
  data_juicer/utils/constant.py
  tests/ops/filter/test_video_tagging_from_frames_filter.py
  tests/ops/mapper/test_image_tagging_mapper.py
  tests/ops/mapper/test_video_tagging_from_audio_mapper.py
  tests/ops/mapper/test_video_tagging_from_frames_mapper.py
Labels: enhancement, dj:core

#511 support ray actor
  data_juicer/config/config.py
  data_juicer/core/ray_data.py
  data_juicer/ops/base_op.py
  data_juicer/utils/process_utils.py
  tests/tools/test_process_data.py
Labels: dj:dist, dj:efficiency

#517 fix bug in generate_qa_from_example_mapper
  data_juicer/ops/mapper/generate_qa_from_examples_mapper.py
  tests/ops/mapper/test_generate_qa_from_examples_mapper.py
Labels: bug, dj:op

#514 Format conversion tools for post tuning datasets
  README.md
  README_ZH.md
  tools/fmt_conversion/README.md
  tools/fmt_conversion/README_ZH.md
  tools/fmt_conversion/multimodal/README.md
  tools/fmt_conversion/multimodal/README_ZH.md
  tools/fmt_conversion/multimodal/absolute_path_to_relative_path.py
  tools/fmt_conversion/multimodal/data_juicer_format_to_target_format/dj_to_internvid.py
  tools/fmt_conversion/multimodal/data_juicer_format_to_target_format/dj_to_llava.py
  tools/fmt_conversion/multimodal/data_juicer_format_to_target_format/dj_to_mmc4.py
  tools/fmt_conversion/multimodal/data_juicer_format_to_target_format/dj_to_msrvtt.py
  tools/fmt_conversion/multimodal/data_juicer_format_to_target_format/dj_to_video_chatgpt.py
  tools/fmt_conversion/multimodal/data_juicer_format_to_target_format/dj_to_wavcaps.py
  tools/fmt_conversion/multimodal/data_juicer_format_to_target_format/dj_to_youku.py
  tools/fmt_conversion/multimodal/source_format_to_data_juicer_format/internvid_to_dj.py
  tools/fmt_conversion/multimodal/source_format_to_data_juicer_format/llava_to_dj.py
  tools/fmt_conversion/multimodal/source_format_to_data_juicer_format/mmc4_to_dj.py
  tools/fmt_conversion/multimodal/source_format_to_data_juicer_format/msrvtt_to_dj.py
  tools/fmt_conversion/multimodal/source_format_to_data_juicer_format/video_chatgpt_to_dj.py
  tools/fmt_conversion/multimodal/source_format_to_data_juicer_format/wavcaps_to_dj.py
  tools/fmt_conversion/multimodal/source_format_to_data_juicer_format/youku_to_dj.py
  tools/fmt_conversion/multimodal/utils.py
  tools/fmt_conversion/post_tuning_dialog/README.md
  tools/fmt_conversion/post_tuning_dialog/README_ZH.md
  tools/fmt_conversion/post_tuning_dialog/data_juicer_format_to_target_format/dj_to_alpaca.py
  tools/fmt_conversion/post_tuning_dialog/data_juicer_format_to_target_format/dj_to_llama_factory_sharegpt.py
  tools/fmt_conversion/post_tuning_dialog/data_juicer_format_to_target_format/dj_to_messages.py
  tools/fmt_conversion/post_tuning_dialog/data_juicer_format_to_target_format/dj_to_ms_swift_sharegpt.py
  tools/fmt_conversion/post_tuning_dialog/source_format_to_data_juicer_format/alpaca_to_dj.py
  tools/fmt_conversion/post_tuning_dialog/source_format_to_data_juicer_format/llama_factory_sharegpt_to_dj.py
  tools/fmt_conversion/post_tuning_dialog/source_format_to_data_juicer_format/messages_to_dj.py
  tools/fmt_conversion/post_tuning_dialog/source_format_to_data_juicer_format/ms_swift_sharegpt_to_dj.py
Labels: documentation, enhancement, dj:dataset, dj:tools

#521 Fix operators doc link for aggregators
  configs/config_all.yaml
  tests/ops/aggregator/__init__.py
  tests/ops/aggregator/test_entity_attribute_aggregator.py
  tests/ops/aggregator/test_most_relavant_entities_aggregator.py
  tests/ops/aggregator/test_nested_aggregator.py
Labels: documentation

#502 Add minhash deduplicator based on RAY.
  configs/config_all.yaml
  data_juicer/config/config.py
  data_juicer/core/ray_data.py
  data_juicer/core/ray_executor.py
  data_juicer/ops/base_op.py
  data_juicer/ops/deduplicator/__init__.py
  data_juicer/ops/deduplicator/ray_bts_minhash_deduplicator.py
  data_juicer/utils/constant.py
  docs/Operators.md
  docs/Operators_ZH.md
  environments/dist_requires.txt
  tests/config/test_config_funcs.py
Labels: dj:op, dj:dist, dj:efficiency
