Repository modelscope/data-juicer, pull requests merged in 2024-09, with the labels that each got.

#393 Add image_pair_similarity_filter
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/image_pair_similarity_filter.py
  data_juicer/utils/constant.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/filter/test_image_pair_similarity_filter.py
Labels: enhancement, dj:multimodal, dj:op

#402 Add turbo mode
  data_juicer/config/config.py
  data_juicer/core/data.py
  data_juicer/ops/base_op.py
  tests/config/test_config_funcs.py
Labels: enhancement

#427 Fix some words
  configs/data_juicer_recipes/general-video-refine-example.yaml
  configs/demo/bench/model_train.yaml
  configs/demo/bench/model_train_2_epoch.yaml
  configs/demo/sandbox/inception_eval_config.yaml
  data_juicer/utils/compress.py
  data_juicer/utils/constant.py
  data_juicer/utils/file_utils.py
  data_juicer/utils/fingerprint_utils.py
  tools/mm_eval/inception_metrics/README.md
  tools/mm_eval/inception_metrics/calc_metrics_for_videos.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_llava.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_mmc4.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_video_chatgpt.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_wavcaps.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_youku.py
  tools/multimodal/source_format_to_data_juicer_format/llava_to_dj.py
  tools/multimodal/source_format_to_data_juicer_format/mmc4_to_dj.py
  tools/multimodal/source_format_to_data_juicer_format/video_chatgpt_to_dj.py
  tools/multimodal/source_format_to_data_juicer_format/wavcaps_to_dj.py
  tools/multimodal/source_format_to_data_juicer_format/youku_to_dj.py
  tools/multimodal/utils.py
  tools/preprocess/dataset_split_by_language.py
  tools/preprocess/reformat_jsonl_nan_value.py
  tools/quality_classifier/qc_utils.py
  tools/sandbox_starter.py
Labels: enhancement

#423 Add new OP: image_tagging_mapper
  configs/config_all.yaml
  data_juicer/ops/filter/video_tagging_from_frames_filter.py
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/image_tagging_mapper.py
  data_juicer/ops/mapper/video_tagging_from_audio_mapper.py
  data_juicer/ops/mapper/video_tagging_from_frames_mapper.py
  data_juicer/utils/constant.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/mapper/test_image_tagging_mapper.py
  tests/ops/mapper/test_video_tagging_from_audio_mapper.py
  tests/ops/mapper/test_video_tagging_from_frames_mapper.py
Labels: dj:multimodal, dj:op

#434 doc update for sandbox paper
  configs/data_juicer_recipes/README.md
  configs/data_juicer_recipes/README_ZH.md
  configs/data_juicer_recipes/data-juicer-sandbox-optimal.yaml
  configs/data_juicer_recipes/data-juicer-sandbox-self-evolution.yaml
  docs/Sandbox-ZH.md
  docs/Sandbox.md
Labels: documentation

#414 Add lazy import and auto-install dependencies
  data_juicer/ops/base_op.py
  data_juicer/ops/deduplicator/document_minhash_deduplicator.py
  data_juicer/ops/deduplicator/document_simhash_deduplicator.py
  data_juicer/ops/deduplicator/image_deduplicator.py
  data_juicer/ops/deduplicator/ray_image_deduplicator.py
  data_juicer/ops/filter/alphanumeric_filter.py
  data_juicer/ops/filter/flagged_words_filter.py
  data_juicer/ops/filter/image_aesthetics_filter.py
  data_juicer/ops/filter/image_face_ratio_filter.py
  data_juicer/ops/filter/image_nsfw_filter.py
  data_juicer/ops/filter/image_text_matching_filter.py
  data_juicer/ops/filter/image_text_similarity_filter.py
  data_juicer/ops/filter/image_watermark_filter.py
  data_juicer/ops/filter/language_id_score_filter.py
  data_juicer/ops/filter/perplexity_filter.py
  data_juicer/ops/filter/phrase_grounding_recall_filter.py
  data_juicer/ops/filter/stopwords_filter.py
  data_juicer/ops/filter/text_action_filter.py
  data_juicer/ops/filter/text_entity_dependency_filter.py
  data_juicer/ops/filter/token_num_filter.py
  data_juicer/ops/filter/video_aesthetics_filter.py
  data_juicer/ops/filter/video_frames_text_similarity_filter.py
  data_juicer/ops/filter/video_motion_score_filter.py
  data_juicer/ops/filter/video_nsfw_filter.py
  data_juicer/ops/filter/video_ocr_area_ratio_filter.py
  data_juicer/ops/filter/video_tagging_from_frames_filter.py
  data_juicer/ops/filter/video_watermark_filter.py
  data_juicer/ops/filter/word_repetition_filter.py
  data_juicer/ops/filter/words_num_filter.py
  data_juicer/ops/mapper/audio_ffmpeg_wrapped_mapper.py
  data_juicer/ops/mapper/chinese_convert_mapper.py
  data_juicer/ops/mapper/clean_html_mapper.py
  data_juicer/ops/mapper/fix_unicode_mapper.py
  data_juicer/ops/mapper/image_captioning_mapper.py
  data_juicer/ops/mapper/image_diffusion_mapper.py
  data_juicer/ops/mapper/image_face_blur_mapper.py
  data_juicer/ops/mapper/nlpaug_en_mapper.py
  data_juicer/ops/mapper/nlpcda_zh_mapper.py
  data_juicer/ops/mapper/remove_words_with_incorrect_substrings_mapper.py
  data_juicer/ops/mapper/sentence_split_mapper.py
  data_juicer/ops/mapper/video_captioning_from_audio_mapper.py
  data_juicer/ops/mapper/video_captioning_from_frames_mapper.py
  data_juicer/ops/mapper/video_captioning_from_summarizer_mapper.py
  data_juicer/ops/mapper/video_captioning_from_video_mapper.py
  data_juicer/ops/mapper/video_face_blur_mapper.py
  data_juicer/ops/mapper/video_ffmpeg_wrapped_mapper.py
  data_juicer/ops/mapper/video_remove_watermark_mapper.py
  data_juicer/ops/mapper/video_resize_aspect_ratio_mapper.py
  data_juicer/ops/mapper/video_resize_resolution_mapper.py
  data_juicer/ops/mapper/video_split_by_scene_mapper.py
  data_juicer/ops/mapper/video_tagging_from_audio_mapper.py
  data_juicer/ops/mapper/video_tagging_from_frames_mapper.py
  data_juicer/utils/auto_install_utils.py
  data_juicer/utils/availability_utils.py
  data_juicer/utils/model_utils.py
  data_juicer/utils/unittest_utils.py
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  environments/science_requires.txt
  tests/ops/filter/test_video_aesthetics_filter.py
Labels: enhancement
