Repository modelscope/data-juicer, pull requests merged in 2024-11, with the labels that each got.

#460 unittest opt
  .coveragerc
  data_juicer/ops/mapper/remove_table_text_mapper.py
  data_juicer/utils/model_utils.py
  data_juicer/utils/unittest_utils.py
  environments/dev_requires.txt
  tests/core/test_monitor.py
  tests/ops/filter/test_image_aesthetics_filter.py
  tests/ops/filter/test_image_face_count_filter.py
  tests/ops/filter/test_image_face_ratio_filter.py
  tests/ops/filter/test_image_nsfw_filter.py
  tests/ops/filter/test_image_text_matching_filter.py
  tests/ops/filter/test_image_watermark_filter.py
  tests/ops/filter/test_phrase_grounding_recall_filter.py
  tests/ops/filter/test_video_aesthetics_filter.py
  tests/ops/filter/test_video_nsfw_filter.py
  tests/ops/filter/test_video_ocr_area_ratio_filter.py
  tests/ops/filter/test_video_tagging_from_frames_filter.py
  tests/ops/filter/test_video_watermark_filter.py
  tests/ops/mapper/test_extract_qa_mapper.py
  tests/ops/mapper/test_generate_instruction_mapper.py
  tests/ops/mapper/test_image_captioning_mapper.py
  tests/ops/mapper/test_image_diffusion_mapper.py
  tests/ops/mapper/test_image_tagging_mapper.py
  tests/ops/mapper/test_nlpcda_zh_mapper.py
  tests/ops/mapper/test_optimize_instruction_mapper.py
  tests/ops/mapper/test_video_captioning_from_audio_mapper.py
  tests/ops/mapper/test_video_captioning_from_frames_mapper.py
  tests/ops/mapper/test_video_captioning_from_summarizer_mapper.py
  tests/ops/mapper/test_video_captioning_from_video_mapper.py
  tests/ops/mapper/test_video_remove_watermark_mapper.py
  tests/ops/mapper/test_video_split_by_scene_mapper.py
  tests/ops/mapper/test_video_tagging_from_frames_mapper.py
  tests/ops/test_op_fusion.py
  tests/run.py
Labels: enhancement, priority:high

#454 [Ready] align sft formats & new ops
  configs/config_all.yaml
  data_juicer/core/data.py
  data_juicer/ops/base_op.py
  data_juicer/ops/common/__init__.py
  data_juicer/ops/deduplicator/__init__.py
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/extract_qa_mapper.py
  data_juicer/ops/mapper/generate_instruction_mapper.py
  data_juicer/ops/mapper/generate_qa_from_examples_mapper.py
  data_juicer/ops/mapper/generate_qa_from_text_mapper.py
  data_juicer/ops/mapper/optimize_instruction_mapper.py
  data_juicer/ops/mapper/optimize_qa_mapper.py
  data_juicer/ops/mapper/optimize_query_mapper.py
  data_juicer/ops/mapper/optimize_response_mapper.py
  data_juicer/utils/auto_install_mapping.py
  data_juicer/utils/model_utils.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/config/test_config_funcs.py
  tests/ops/mapper/test_extract_qa_mapper.py
  tests/ops/mapper/test_generate_instruction_mapper.py
  tests/ops/mapper/test_generate_qa_from_examples_mapper.py
  tests/ops/mapper/test_generate_qa_from_text_mapper.py
  tests/ops/mapper/test_image_tagging_mapper.py
  tests/ops/mapper/test_optimize_instruction_mapper.py
  tests/ops/mapper/test_optimize_qa_mapper.py
  tests/ops/mapper/test_optimize_query_mapper.py
  tests/ops/mapper/test_optimize_response_mapper.py
Labels: enhancement

#472 Optimize OP docs for better usage
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/filter/test_stopwords_filter.py
  tests/ops/filter/test_words_num_filter.py
Labels: documentation, enhancement

#463 [Ready] Add API Call & Example OPs
  .github/workflows/docker/docker-compose.yml
  configs/config_all.yaml
  data_juicer/core/data.py
  data_juicer/ops/filter/image_pair_similarity_filter.py
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/calibrate_qa_mapper.py
  data_juicer/ops/mapper/calibrate_query_mapper.py
  data_juicer/ops/mapper/calibrate_response_mapper.py
  data_juicer/ops/mapper/optimize_qa_mapper.py
  data_juicer/utils/mm_utils.py
  data_juicer/utils/model_utils.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/filter/test_image_aesthetics_filter.py
  tests/ops/filter/test_image_face_count_filter.py
  tests/ops/filter/test_image_face_ratio_filter.py
  tests/ops/filter/test_image_nsfw_filter.py
  tests/ops/filter/test_image_watermark_filter.py
  tests/ops/filter/test_phrase_grounding_recall_filter.py
  tests/ops/filter/test_video_aesthetics_filter.py
  tests/ops/filter/test_video_ocr_area_ratio_filter.py
  tests/ops/mapper/test_calibrate_qa_mapper.py
  tests/ops/mapper/test_calibrate_query_mapper.py
  tests/ops/mapper/test_calibrate_response_mapper.py
  tests/ops/mapper/test_video_split_by_scene_mapper.py
  tests/ops/test_op_fusion.py
  tests/run.py
Labels: enhancement

#468 [Ready] Basic Service Implementation
  .pre-commit-config.yaml
  data_juicer/config/__init__.py
  data_juicer/config/config.py
  data_juicer/core/analyzer.py
  data_juicer/core/executor.py
  data_juicer/ops/base_op.py
  demos/api_service/configs/dj_config_template.yaml
  demos/api_service/configs/model_configs.json
  demos/api_service/react_data_filter_process.ipynb
  demos/api_service/react_data_mapper_process.ipynb
  demos/api_service/utils.py
  demos/api_service/wrapped_filters.py
  demos/api_service/wrapped_mappers.py
  demos/data/demo-dataset-images.jsonl
  demos/data/demo-dataset_1725870268.jsonl
  demos/data/demo-dataset_1725870628.jsonl
  environments/minimal_requires.txt
  service.py
Labels: enhancement

#479 [Ready] support API retry
  data_juicer/ops/mapper/calibrate_qa_mapper.py
  data_juicer/utils/model_utils.py
  tests/ops/mapper/test_calibrate_qa_mapper.py
Labels: enhancement

#484 update readme
  README.md
  README_ZH.md
Labels: documentation, dj:dist

#481 Dev/llm info extract
  configs/config_all.yaml
  data_juicer/ops/common/__init__.py
  data_juicer/ops/common/helper_func.py
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/calibrate_qa_mapper.py
  data_juicer/ops/mapper/extract_entity_attribute_mapper.py
  data_juicer/ops/mapper/extract_entity_relation_mapper.py
  data_juicer/ops/mapper/extract_event_mapper.py
  data_juicer/ops/mapper/extract_keyword_mapper.py
  data_juicer/ops/mapper/extract_nickname_mapper.py
  data_juicer/ops/mapper/generate_qa_from_examples_mapper.py
  data_juicer/ops/mapper/optimize_qa_mapper.py
  data_juicer/ops/mapper/text_chunk_mapper.py
  data_juicer/utils/common_utils.py
  data_juicer/utils/constant.py
  data_juicer/utils/model_utils.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/mapper/test_extract_entity_attribute_mapper.py
  tests/ops/mapper/test_extract_entity_relation_mapper.py
  tests/ops/mapper/test_extract_event_mapper.py
  tests/ops/mapper/test_extract_keyword_mapper.py
  tests/ops/mapper/test_extract_nickname_mapper.py
  tests/ops/mapper/test_text_chunk_mapper.py
Labels: documentation, dj:op, agent

#494 Auto docker image building on release
  .github/workflows/publish-docker.yml
  .github/workflows/unit-test.yml
  Dockerfile
Labels: enhancement, priority:high

#464 Probe-based OP Fusion & Reordering
  configs/config_all.yaml
  data_juicer/config/config.py
  data_juicer/core/adapter.py
  data_juicer/core/analyzer.py
  data_juicer/core/data.py
  data_juicer/core/executor.py
  data_juicer/core/monitor.py
  data_juicer/core/ray_executor.py
  data_juicer/ops/filter/image_aspect_ratio_filter.py
  data_juicer/ops/filter/image_shape_filter.py
  data_juicer/ops/filter/image_size_filter.py
  data_juicer/ops/filter/image_text_similarity_filter.py
  data_juicer/ops/load.py
  data_juicer/ops/op_fusion.py
  tests/core/test_adapter.py
  tests/ops/test_op_fusion.py
Labels: enhancement, dj:op

#501 Fix dependency conflicts for docker building
  Dockerfile
  README.md
  README_ZH.md
  environments/minimal_requires.txt
Labels: bug, documentation, dj-ci/cd
