Repository modelscope/data-juicer, pull requests merged in 2024-02, with the labels that each got.

#195 Docs/bad data exhibition
  .github/workflows/unit-test.yml
  README.md
  README_ZH.md
  configs/config_all.yaml
  data_juicer/utils/mm_utils.py
  docs/BadDataExhibition.md
  docs/BadDataExhibition_ZH.md
  tools/multimodal/data_juicer_format_to_target_format/dj_to_mmc4.py
  tools/multimodal/source_format_to_data_juicer_format/mmc4_to_dj.py
Labels: documentation

#211 set up awesome-llm-data; minor update for homepage
  README.md
  README_ZH.md
  docs/awesome_llm_data.md
Labels: documentation, good first issue

#203 Enhance/gpu support
  data_juicer/__init__.py
  data_juicer/core/executor.py
  data_juicer/ops/base_op.py
  data_juicer/ops/deduplicator/document_simhash_deduplicator.py
  data_juicer/ops/filter/alphanumeric_filter.py
  data_juicer/ops/filter/image_text_matching_filter.py
  data_juicer/ops/filter/image_text_similarity_filter.py
  data_juicer/ops/filter/phrase_grounding_recall_filter.py
  data_juicer/ops/filter/token_num_filter.py
  data_juicer/ops/mapper/generate_caption_mapper.py
  data_juicer/utils/model_utils.py
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  tests/ops/filter/test_image_text_matching_filter.py
  tests/ops/filter/test_image_text_similarity_filter.py
  tests/ops/filter/test_phrase_grounding_recall_filter.py
  tests/ops/mapper/test_generate_caption_mapper.py
  tests/ops/test_op_fusion.py
Labels: enhancement, dj:multimodal

#217 fix single gpu case
  data_juicer/utils/model_utils.py
Labels: bug, enhancement

#208 * update dockerfile with jdk
  Dockerfile
  README.md
  README_ZH.md
Labels: enhancement

#200 image diffusion mapper
  .github/workflows/unit-test.yml
  configs/config_all.yaml
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/image_diffusion_mapper.py
  data_juicer/utils/model_utils.py
  docs/Operators.md
  docs/Operators_ZH.md
  environments/science_requires.txt
  tests/ops/mapper/test_image_diffusion_mapper.py
Labels: enhancement, dj:multimodal

#219 fix bad link in homepage
  README.md
Labels: documentation

#220 batch op in developer guidance
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
Labels: documentation
