Repository modelscope/data-juicer, pull requests merged in 2024-03, with the labels that each got.

#222 Refine _cuda_device_count logic
  data_juicer/__init__.py
  data_juicer/utils/availability_utils.py
Labels: bug

#234 fix the toc links in DJ_SORA.md
  docs/DJ_SORA.md
Labels: documentation

#235 Minor modification in scripts
  scripts/dlc/partition_data_dlc.py
  scripts/dlc/run_on_dlc.sh
Labels: dj:dist

#239 debug video_key and to_bytes
  data_juicer/config/config.py
  data_juicer/format/formatter.py
  data_juicer/ops/deduplicator/video_deduplicator.py
Labels: bug

#243 fix cut video bugs (#241)
  data_juicer/ops/mapper/video_split_by_duration_mapper.py
  data_juicer/ops/mapper/video_split_by_key_frame_mapper.py
  data_juicer/utils/mm_utils.py
  tools/multimodal/source_format_to_data_juicer_format/internvid_to_dj.py
Labels: bug

#245 Update sphinx docs for v0.2.0
  data_juicer/analysis/column_wise_analysis.py
  data_juicer/analysis/draw.py
  data_juicer/config/config.py
  data_juicer/core/ray_executor.py
  data_juicer/ops/common/helper_func.py
  data_juicer/ops/filter/audio_size_filter.py
  data_juicer/ops/filter/image_size_filter.py
  data_juicer/ops/mapper/chinese_convert_mapper.py
  data_juicer/ops/mapper/fix_unicode_mapper.py
  data_juicer/ops/mapper/generate_caption_mapper.py
  data_juicer/ops/mapper/image_blur_mapper.py
  data_juicer/ops/mapper/image_captioning_mapper.py
  data_juicer/ops/mapper/image_diffusion_mapper.py
  data_juicer/ops/mapper/video_captioning_from_video_mapper.py
  data_juicer/ops/mapper/video_split_by_duration_mapper.py
  data_juicer/utils/ckpt_utils.py
  data_juicer/utils/compress.py
  data_juicer/utils/file_utils.py
  data_juicer/utils/mm_utils.py
  docs/sphinx_doc/source/data_juicer.analysis.rst
  docs/sphinx_doc/source/data_juicer.config.rst
  docs/sphinx_doc/source/data_juicer.core.rst
  docs/sphinx_doc/source/data_juicer.format.rst
  docs/sphinx_doc/source/data_juicer.ops.common.rst
  docs/sphinx_doc/source/data_juicer.ops.deduplicator.rst
  docs/sphinx_doc/source/data_juicer.ops.filter.rst
  docs/sphinx_doc/source/data_juicer.ops.mapper.rst
  docs/sphinx_doc/source/data_juicer.ops.rst
  docs/sphinx_doc/source/data_juicer.ops.selector.rst
  docs/sphinx_doc/source/data_juicer.utils.rst
Labels: documentation

#236 remove watermark mapper
  configs/config_all.yaml
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/video_remove_watermark_mapper.py
  data_juicer/ops/mapper/video_split_by_duration_mapper.py
  data_juicer/ops/mapper/video_split_by_key_frame_mapper.py
  data_juicer/utils/mm_utils.py
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  docs/Operators.md
  docs/Operators_ZH.md
  docs/sphinx_doc/source/data_juicer.ops.mapper.rst
  environments/science_requires.txt
  tests/ops/mapper/test_video_remove_watermark_mapper.py
Labels: enhancement, dj:multimodal, dj:op

#247 fix nested dir bug
  data_juicer/ops/mapper/audio_ffmpeg_wrapped_mapper.py
  data_juicer/ops/mapper/video_ffmpeg_wrapped_mapper.py
  data_juicer/ops/mapper/video_split_by_duration_mapper.py
  data_juicer/ops/mapper/video_split_by_key_frame_mapper.py
  data_juicer/ops/mapper/video_split_by_scene_mapper.py
  data_juicer/utils/constant.py
  data_juicer/utils/file_utils.py
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  tests/ops/mapper/test_video_resize_resolution_mapper.py
Labels: bug

#244 Demos/op insight update
  demos/data_visualization_diversity/app.py
  demos/data_visualization_op_insight/app.css
  demos/data_visualization_op_insight/app.py
  demos/data_visualization_op_insight/cache/.gitkeep
Labels: bug, enhancement, dj:multimodal

#249 ops/image face blur mapper
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/image_face_ratio_filter.py
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/generate_caption_mapper.py
  data_juicer/ops/mapper/gpt4v_generate_mapper.py
  data_juicer/ops/mapper/image_face_blur_mapper.py
  docs/Operators.md
  docs/Operators_ZH.md
  docs/sphinx_doc/source/data_juicer.ops.filter.rst
  docs/sphinx_doc/source/data_juicer.ops.mapper.rst
  tests/ops/filter/test_image_face_ratio_filter.py
  tests/ops/mapper/test_image_face_blur_mapper.py
Labels: enhancement, dj:multimodal, dj:op

#252 Dev/nsfw filter
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/image_nsfw_filter.py
  data_juicer/ops/filter/video_nsfw_filter.py
  data_juicer/ops/filter/video_resolution_filter.py
  data_juicer/ops/mapper/video_remove_watermark_mapper.py
  data_juicer/utils/constant.py
  docs/Operators.md
  docs/Operators_ZH.md
  docs/sphinx_doc/source/data_juicer.ops.filter.rst
  tests/ops/deduplicator/test_image_deduplicator.py
  tests/ops/deduplicator/test_video_deduplicator.py
  tests/ops/filter/test_image_nsfw_filter.py
  tests/ops/filter/test_video_nsfw_filter.py
  tests/ops/mapper/test_video_remove_watermark_mapper.py
Labels: documentation, enhancement, dj:multimodal, dj:op

#253 Op/video face blur mapper
  configs/config_all.yaml
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/video_face_blur_mapper.py
  data_juicer/ops/mapper/video_remove_watermark_mapper.py
  data_juicer/utils/mm_utils.py
  docs/Operators.md
  docs/Operators_ZH.md
  docs/sphinx_doc/source/data_juicer.ops.mapper.rst
  tests/ops/mapper/test_video_face_blur_mapper.py
Labels: enhancement, dj:multimodal

#259 pass args to scenedetect by keywords
  data_juicer/ops/mapper/video_split_by_scene_mapper.py
Labels: bug, dj:multimodal, dj:op

#263 Add exact match deduplicator based on ray and redis
  README.md
  README_ZH.md
  configs/config_all.yaml
  data_juicer/ops/deduplicator/__init__.py
  data_juicer/ops/deduplicator/ray_basic_deduplicator.py
  data_juicer/ops/deduplicator/ray_document_deduplicator.py
  data_juicer/ops/deduplicator/ray_image_deduplicator.py
  data_juicer/ops/deduplicator/ray_video_deduplicator.py
  data_juicer/utils/constant.py
  demos/process_video_on_ray/configs/demo.yaml
  docs/Operators.md
  docs/Operators_ZH.md
  environments/dist_requires.txt
Labels: enhancement, dj:op, dj:dist

#260 Dev/filter according tags
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/video_tagging_from_frames_filter.py
  docs/Operators.md
  docs/Operators_ZH.md
  docs/sphinx_doc/source/data_juicer.ops.filter.rst
  tests/ops/filter/test_video_tagging_from_frames_filter.py
Labels: documentation, enhancement, dj:multimodal, dj:op

#265 Update readme for ffmpeg installation
  README.md
  README_ZH.md
Labels: documentation

#250 Op/video captioning from summarizer mapper
  configs/config_all.yaml
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/remove_header_mapper.py
  data_juicer/ops/mapper/video_captioning_from_summarizer_mapper.py
  docs/Operators.md
  docs/Operators_ZH.md
  docs/sphinx_doc/source/data_juicer.ops.mapper.rst
  tests/ops/mapper/test_video_captioning_from_summarizer_mapper.py
Labels: enhancement, dj:multimodal, dj:op

#272 Doc/update dj sora docs
  README.md
  README_ZH.md
  docs/DJ_SORA.md
  docs/DJ_SORA_ZH.md
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/filter/test_image_aesthetics_filter.py
  tests/ops/filter/test_image_nsfw_filter.py
  tests/ops/filter/test_image_text_matching_filter.py
  tests/ops/filter/test_image_watermark_filter.py
  tests/ops/filter/test_phrase_grounding_recall_filter.py
  tests/ops/filter/test_video_aesthetics_filter.py
  tests/ops/filter/test_video_nsfw_filter.py
  tests/ops/filter/test_video_ocr_area_ratio_filter.py
  tests/ops/filter/test_video_tagging_from_frames_filter.py
  tests/ops/filter/test_video_watermark_filter.py
  tests/ops/mapper/test_video_split_by_scene_mapper.py
  tests/ops/mapper/test_video_tagging_from_audio_mapper.py
  tests/ops/mapper/test_video_tagging_from_frames_mapper.py
Labels: documentation

#274 Enable GPU usage for ray executor
  data_juicer/core/ray_executor.py
Labels: enhancement

#275 fixed diffusion model loading
  configs/config_all.yaml
  data_juicer/ops/mapper/image_diffusion_mapper.py
  data_juicer/utils/model_utils.py
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  tests/ops/mapper/test_image_diffusion_mapper.py
Labels: bug

#279 fix tutorial 6 and 7
  configs/config_all.yaml
  data_juicer/ops/mapper/image_diffusion_mapper.py
  data_juicer/utils/model_utils.py
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  tests/ops/mapper/test_image_diffusion_mapper.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_llava.py
  tools/multimodal/source_format_to_data_juicer_format/llava_to_dj.py
  tutorials/06_develop_a_new_operator.ipynb
  tutorials/07_use_tool_pool.ipynb
Labels: documentation, enhancement, dj:multimodal

#270 Make num_process OP-aware
  configs/config_all.yaml
  data_juicer/core/executor.py
  data_juicer/core/ray_executor.py
  data_juicer/ops/base_op.py
  data_juicer/ops/filter/video_aesthetics_filter.py
  data_juicer/utils/model_utils.py
Labels: enhancement

#282 Fix Memory Warning Message
  data_juicer/core/executor.py
Labels: bug
