Repository modelscope/data-juicer, pull requests merged in 2024-04, with the labels that each got.

#284 Add Ray actor
  README.md
  README_ZH.md
  data_juicer/core/executor.py
  data_juicer/core/ray_executor.py
  data_juicer/ops/base_op.py
  data_juicer/utils/process_utils.py
Labels: enhancement, dj:dist

#288 convert absolute path to relative path for multi sources
  data_juicer/utils/file_utils.py
  environments/preprocess_requires.txt
  tools/multimodal/README.md
  tools/multimodal/README_ZH.md
  tools/multimodal/absolute_path_to_relative_path.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_internvid.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_llava.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_mmc4.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_msrvtt.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_video_chatgpt.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_youku.py
  tools/multimodal/source_format_to_data_juicer_format/llava_to_dj.py
Labels: bug, documentation, enhancement, dj:multimodal

#294 [Hot fix] optimize convert to absolute path map
  data_juicer/core/ray_executor.py
Labels: dj:dist

#271 Enhance/op fusion video
  README.md
  README_ZH.md
  data_juicer/ops/deduplicator/ray_basic_deduplicator.py
  data_juicer/ops/filter/video_aesthetics_filter.py
  data_juicer/ops/filter/video_frames_text_similarity_filter.py
  data_juicer/ops/filter/video_motion_score_filter.py
  data_juicer/ops/filter/video_nsfw_filter.py
  data_juicer/ops/filter/video_ocr_area_ratio_filter.py
  data_juicer/ops/filter/video_watermark_filter.py
  data_juicer/ops/op_fusion.py
  data_juicer/utils/constant.py
Labels: enhancement, dj:multimodal

#295 Fix: avoid extracting empty frame list
  .github/workflows/unit-test.yml
  data_juicer/utils/mm_utils.py
  tests/config/test_config_funcs.py
  tests/ops/mapper/test_image_diffusion_mapper.py
Labels: bug, priority:high, dj:multimodal

#290 Document deduplication tools using pyspark.
  tools/distributed_deduplication/README.md
  tools/distributed_deduplication/README_ZH.md
  tools/distributed_deduplication/__init__.py
  tools/distributed_deduplication/dedup_utils.py
  tools/distributed_deduplication/spark_dedup.py
Labels: dj:dist

#300 fix Bug: KeyError: 'text' Corresponding to issue #296
  data_juicer/config/config.py
Labels: bug

#299 Reformat API doc and generate docs automatically
  .github/workflows/deploy_sphinx_docs.yml
  data_juicer/analysis/__init__.py
  data_juicer/config/__init__.py
  data_juicer/core/__init__.py
  data_juicer/format/__init__.py
  data_juicer/ops/__init__.py
  data_juicer/ops/common/__init__.py
  data_juicer/ops/common/helper_func.py
  data_juicer/ops/deduplicator/__init__.py
  data_juicer/ops/deduplicator/ray_document_deduplicator.py
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/image_face_blur_mapper.py
  data_juicer/ops/mapper/video_face_blur_mapper.py
  data_juicer/ops/selector/__init__.py
  data_juicer/utils/process_utils.py
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  docs/sphinx_doc/README.md
  docs/sphinx_doc/README_ZH.md
  docs/sphinx_doc/_templates/module.rst_t
  docs/sphinx_doc/_templates/package.rst_t
  docs/sphinx_doc/_templates/toc.rst_t
  docs/sphinx_doc/build_doc.sh
  docs/sphinx_doc/source/conf.py
  docs/sphinx_doc/source/data_juicer.analysis.rst
  docs/sphinx_doc/source/data_juicer.config.rst
  docs/sphinx_doc/source/data_juicer.core.rst
  docs/sphinx_doc/source/data_juicer.format.rst
  docs/sphinx_doc/source/data_juicer.ops.common.rst
  docs/sphinx_doc/source/data_juicer.ops.deduplicator.rst
  docs/sphinx_doc/source/data_juicer.ops.filter.rst
  docs/sphinx_doc/source/data_juicer.ops.mapper.rst
  docs/sphinx_doc/source/data_juicer.ops.rst
  docs/sphinx_doc/source/data_juicer.ops.selector.rst
  docs/sphinx_doc/source/data_juicer.rst
  docs/sphinx_doc/source/data_juicer.tools.rst
  docs/sphinx_doc/source/data_juicer.utils.rst
  docs/sphinx_doc/source/index.rst
  docs/sphinx_doc/source/modules.rst
  environments/minimal_requires.txt
Labels: documentation

#301 * fix several bugs
  data_juicer/ops/deduplicator/document_minhash_deduplicator.py
  data_juicer/ops/deduplicator/document_simhash_deduplicator.py
  data_juicer/ops/mapper/chinese_convert_mapper.py
Labels: bug

#291 implement data-model sandbox, with refactoring existing DJ's features and tools
  README.md
  README_ZH.md
  configs/config_all.yaml
  configs/demo/sandbox/gpt3_data_quality_eval_config.yaml
  configs/demo/sandbox/gpt3_extra_train_config.json
  configs/demo/sandbox/gpt3_extra_train_config.yaml
  configs/demo/sandbox/sandbox.yaml
  data_juicer/config/config.py
  data_juicer/core/executor.py
  data_juicer/core/sandbox/evaluators.py
  data_juicer/core/sandbox/factories.py
  data_juicer/core/sandbox/model_executors.py
  data_juicer/core/sandbox/pipelines.py
  data_juicer/format/mixture_formatter.py
  data_juicer/utils/file_utils.py
  docs/DJ_SORA.md
  docs/DJ_SORA_ZH.md
  docs/Sandbox-ZH.md
  docs/Sandbox.md
  tests/ops/filter/test_video_tagging_from_frames_filter.py
  tests/run.py
  tools/hpo/execute_hpo_3sigma.py
  tools/sandbox_starter.py
Labels: enhancement

#303 Fix/several minor bugs
  data_juicer/__init__.py
  data_juicer/config/config.py
  data_juicer/utils/logger_utils.py
  data_juicer/utils/mm_utils.py
  environments/minimal_requires.txt
Labels: bug, enhancement
