Repository modelscope/data-juicer, pull requests merged in 2024-08, with the labels that each got.

#374 fix video memory leak
  data_juicer/ops/base_op.py
  data_juicer/ops/deduplicator/ray_video_deduplicator.py
  data_juicer/ops/deduplicator/video_deduplicator.py
  data_juicer/ops/filter/video_aesthetics_filter.py
  data_juicer/ops/filter/video_aspect_ratio_filter.py
  data_juicer/ops/filter/video_duration_filter.py
  data_juicer/ops/filter/video_frames_text_similarity_filter.py
  data_juicer/ops/filter/video_nsfw_filter.py
  data_juicer/ops/filter/video_ocr_area_ratio_filter.py
  data_juicer/ops/filter/video_resolution_filter.py
  data_juicer/ops/filter/video_watermark_filter.py
  data_juicer/ops/mapper/video_captioning_from_frames_mapper.py
  data_juicer/ops/mapper/video_captioning_from_video_mapper.py
  data_juicer/ops/mapper/video_face_blur_mapper.py
  data_juicer/ops/mapper/video_remove_watermark_mapper.py
  data_juicer/ops/mapper/video_resize_aspect_ratio_mapper.py
  data_juicer/ops/mapper/video_resize_resolution_mapper.py
  data_juicer/ops/mapper/video_split_by_duration_mapper.py
  data_juicer/ops/mapper/video_split_by_key_frame_mapper.py
  data_juicer/ops/mapper/video_tagging_from_frames_mapper.py
  data_juicer/ops/op_fusion.py
  data_juicer/utils/mm_utils.py
  tests/ops/mapper/test_video_ffmpeg_wrapped_mapper.py
  tests/ops/mapper/test_video_resize_aspect_ratio_mapper.py
  tools/mm_eval/inception_metrics/dataset.py
Labels: bug, dj:multimodal

#364 sandbox bench experiment workflow
  .gitignore
  .pre-commit-config.yaml
  README.md
  README_ZH.md
  configs/config_all.yaml
  configs/data_juicer_recipes/README.md
  configs/data_juicer_recipes/README_ZH.md
  configs/demo/bench/1_single_op_pipline.yaml
  configs/demo/bench/2_multi_op_pipline.yaml
  configs/demo/bench/3_duplicate_pipline.yaml
  configs/demo/bench/model_infer.yaml
  configs/demo/bench/model_train.yaml
  configs/demo/bench/model_train_2_epoch.yaml
  configs/demo/bench/vbench_eval.yaml
  configs/demo/sandbox/sandbox.yaml
  data_juicer/core/sandbox/evaluators.py
  data_juicer/core/sandbox/factories.py
  data_juicer/core/sandbox/hooks.py
  data_juicer/core/sandbox/model_executors.py
  data_juicer/ops/filter/video_aesthetics_filter.py
  data_juicer/ops/filter/video_duration_filter.py
  data_juicer/ops/filter/video_frames_text_similarity_filter.py
  data_juicer/ops/filter/video_nsfw_filter.py
  data_juicer/ops/filter/video_watermark_filter.py
  data_juicer/ops/selector/__init__.py
  data_juicer/ops/selector/random_selector.py
  data_juicer/ops/selector/range_specified_field_selector.py
  data_juicer/ops/selector/topk_specified_field_selector.py
  data_juicer/utils/common_utils.py
  demos/auto_evaluation_helm/README_ZH.md
  demos/data/demo-dataset-videos.jsonl
  docs/Operators.md
  docs/Operators_ZH.md
  docs/Sandbox-ZH.md
  docs/Sandbox.md
  environments/sandbox_requires.txt
  environments/science_requires.txt
  scripts/README.md
  tests/ops/selector/test_random_selector.py
  tests/ops/selector/test_range_specified_field_selector.py
  thirdparty/LLM_ecosystems/README.md
  thirdparty/LLM_ecosystems/README_ZH.md
  thirdparty/LLM_ecosystems/patch/helm.diff
  thirdparty/LLM_ecosystems/patch/megatron.diff
  thirdparty/LLM_ecosystems/setup_helm.sh
  thirdparty/LLM_ecosystems/setup_megatron.sh
  thirdparty/models/README.md
  thirdparty/models/README_ZH.md
  thirdparty/models/patch/easyanimate.diff
  thirdparty/models/setup_easyanimate.sh
  tools/distributed_deduplication/README.md
  tools/distributed_deduplication/README_ZH.md
  tools/hpo/README.md
  tools/hpo/README_ZH.md
  tools/mm_eval/vbench_metrics/README.md
  tools/mm_eval/vbench_metrics/README_ZH.md
  tools/mm_eval/vbench_metrics/VBench_mini_info.json
  tools/multimodal/README.md
  tools/multimodal/README_ZH.md
  tools/sandbox_starter.py
Labels: documentation, enhancement, dj:multimodal

#382 所有涉及到hf_model的算子，都加了一个trust_remote_code的参数并且传递给prepare_model函数
  data_juicer/ops/filter/image_aesthetics_filter.py
  data_juicer/ops/filter/image_nsfw_filter.py
  data_juicer/ops/filter/image_text_matching_filter.py
  data_juicer/ops/filter/image_text_similarity_filter.py
  data_juicer/ops/filter/image_watermark_filter.py
  data_juicer/ops/filter/phrase_grounding_recall_filter.py
  data_juicer/ops/filter/video_aesthetics_filter.py
  data_juicer/ops/filter/video_frames_text_similarity_filter.py
  data_juicer/ops/filter/video_nsfw_filter.py
  data_juicer/ops/filter/video_watermark_filter.py
  data_juicer/ops/mapper/extract_qa_mapper.py
  data_juicer/ops/mapper/image_captioning_mapper.py
  data_juicer/ops/mapper/image_diffusion_mapper.py
  data_juicer/ops/mapper/video_captioning_from_frames_mapper.py
  data_juicer/ops/mapper/video_captioning_from_summarizer_mapper.py
  data_juicer/ops/mapper/video_captioning_from_video_mapper.py
  data_juicer/ops/mapper/video_tagging_from_audio_mapper.py
Labels: enhancement, good first issue, dj:op

#389 + add use_cuda for get_model funcs in two OPs
  data_juicer/ops/filter/video_aesthetics_filter.py
  data_juicer/ops/mapper/image_diffusion_mapper.py
Labels: bug, priority:high

#320 Switch face detection to OpenCV
  configs/config_all.yaml
  data_juicer/ops/filter/image_face_ratio_filter.py
  data_juicer/ops/mapper/image_face_blur_mapper.py
  data_juicer/ops/mapper/video_face_blur_mapper.py
  data_juicer/utils/mm_utils.py
  data_juicer/utils/model_utils.py
  environments/science_requires.txt
  tests/ops/filter/test_image_face_ratio_filter.py
  tests/ops/mapper/test_image_face_blur_mapper.py
  tests/ops/mapper/test_video_face_blur_mapper.py
Labels: enhancement, dj:op

#399 Enhance/ckpt
  data_juicer/core/data.py
  data_juicer/utils/ckpt_utils.py
Labels: bug, enhancement

#397 update spacy to deal conflict with ms-swift
  .github/workflows/docker/docker-compose.yml
  data_juicer/utils/model_utils.py
  environments/minimal_requires.txt
  environments/science_requires.txt
Labels: enhancement
