Repository modelscope/data-juicer, pull requests merged in 2024-01, with the labels that each got.

#165 fix: command line params parser error
  data_juicer/config/config.py
Labels: bug

#167 fix: yapf does not work
  .pre-commit-config.yaml
  data_juicer/analysis/column_wise_analysis.py
  data_juicer/config/config.py
  data_juicer/core/analyser.py
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/language_id_score_filter.py
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/clean_email_mapper.py
  data_juicer/ops/mapper/clean_ip_mapper.py
  data_juicer/ops/mapper/clean_links_mapper.py
  data_juicer/ops/mapper/fix_unicode_mapper.py
  data_juicer/ops/mapper/remove_repeat_sentences_mapper.py
  data_juicer/ops/mapper/replace_content_mapper.py
  data_juicer/utils/availability_utils.py
  data_juicer/utils/constant.py
Labels: bug

#170 fix: change datatype of simhash to string, because pyarrow is incompatible with uint64
  data_juicer/ops/deduplicator/document_simhash_deduplicator.py
Labels: bug

#139 Feature/phrase grounding recall filter
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/phrase_grounding_recall_filter.py
  data_juicer/utils/constant.py
  data_juicer/utils/mm_utils.py
  data_juicer/utils/model_utils.py
  data_juicer/utils/unittest_utils.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/filter/test_image_shape_filter.py
  tests/ops/filter/test_image_text_matching_filter.py
  tests/ops/filter/test_image_text_similarity_filter.py
  tests/ops/filter/test_phrase_grounding_recall_filter.py
  tools/multimodal/data_juicer_format_to_target_format/dj_to_llava.py
  tools/multimodal/source_format_to_data_juicer_format/llava_to_dj.py
Labels: enhancement, dj:multimodal

#171 Release/v0.1.3
  README.md
  README_ZH.md
  data_juicer/__init__.py
  environments/minimal_requires.txt
  tools/multimodal/README.md
  tools/multimodal/README_ZH.md
Labels: documentation

#173 fix: ray compute stats error
  data_juicer/core/ray_executor.py
Labels: bug

#174 add mixture competition
  README.md
  README_ZH.md
Labels: documentation, competition:BetterMixture

#131 added the generated_caption_mapper
  configs/config_all.yaml
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/generate_caption_mapper.py
  data_juicer/utils/mm_utils.py
  data_juicer/utils/model_utils.py
  data_juicer/utils/unittest_utils.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/mapper/test_generate_caption_mapper.py
  tests/run.py
Labels: enhancement, dj:multimodal, dj:op

#178 fix: images will be lost when its path is a abspath
  data_juicer/format/formatter.py
Labels: bug

#181 Fix/import error and keep original sample
  configs/config_all.yaml
  data_juicer/ops/deduplicator/document_simhash_deduplicator.py
  data_juicer/ops/mapper/generate_caption_mapper.py
  data_juicer/ops/mapper/nlpaug_en_mapper.py
  data_juicer/ops/mapper/nlpcda_zh_mapper.py
  tests/ops/mapper/test_generate_caption_mapper.py
  tests/ops/mapper/test_nlpaug_en_mapper.py
  tests/ops/mapper/test_nlpcda_zh_mapper.py
Labels: bug, enhancement

#180 add image blur mapper
  configs/config_all.yaml
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/image_blur_mapper.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/mapper/test_image_blur_mapper.py
Labels: enhancement, dj:multimodal, dj:op

#189 Feature/audio snr filter
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/audio_nmf_snr_filter.py
  data_juicer/utils/constant.py
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/filter/test_audio_nmf_snr_filter.py
Labels: enhancement, dj:multimodal, dj:op

#191 Enhance/support prompt for caption generation
  configs/config_all.yaml
  data_juicer/ops/mapper/generate_caption_mapper.py
Labels: enhancement, dj:multimodal

#196 Refactor/model management (conservative change)
  .github/workflows/unit-test.yml
  app.py
  data_juicer/analysis/diversity_analysis.py
  data_juicer/ops/filter/alphanumeric_filter.py
  data_juicer/ops/filter/flagged_words_filter.py
  data_juicer/ops/filter/image_text_matching_filter.py
  data_juicer/ops/filter/image_text_similarity_filter.py
  data_juicer/ops/filter/language_id_score_filter.py
  data_juicer/ops/filter/perplexity_filter.py
  data_juicer/ops/filter/phrase_grounding_recall_filter.py
  data_juicer/ops/filter/stopwords_filter.py
  data_juicer/ops/filter/token_num_filter.py
  data_juicer/ops/filter/word_num_filter.py
  data_juicer/ops/filter/word_repetition_filter.py
  data_juicer/ops/mapper/generate_caption_mapper.py
  data_juicer/ops/mapper/remove_words_with_incorrect_substrings_mapper.py
  data_juicer/ops/mapper/sentence_split_mapper.py
  data_juicer/utils/model_utils.py
  demos/tool_quality_classifier/quality_classifier/qc_utils.py
  tests/ops/filter/test_image_size_filter.py
  tools/quality_classifier/qc_utils.py
Labels: enhancement

#202 Enhance/face area filter
  data_juicer/ops/filter/face_area_filter.py
Labels: enhancement, dj:multimodal, dj:op
