Repository modelscope/data-juicer, pull requests merged in 2025-06, with the labels that each got.

#684 optimize startup time
  data_juicer/config/config.py
  data_juicer/ops/__init__.py
  data_juicer/ops/base_op.py
  data_juicer/utils/logger_utils.py
  tests/config/test_config.py
  tools/process_data.py
Labels: enhancement, dj:core, dj:efficiency

#696 suppress useless warning from fasttext
  data_juicer/config/config.py
  data_juicer/utils/model_utils.py
  tests/utils/test_model_utils.py
  tools/process_data.py
Labels: enhancement

#686 Refactor sandbox
  .coveragerc
  .github/workflows/docker/docker-compose.yml
  .github/workflows/unit-test-partial.yml
  .github/workflows/unit-test.yml
  .gitignore
  configs/data_juicer_recipes/sandbox/easyanimate_text_to_video/1_single_op_pipeline.yaml
  configs/data_juicer_recipes/sandbox/easyanimate_text_to_video/2_multi_op_pipeline.yaml
  configs/data_juicer_recipes/sandbox/easyanimate_text_to_video/3_duplicate_pipeline.yaml
  configs/data_juicer_recipes/sandbox/easyanimate_text_to_video/model_infer.yaml
  configs/data_juicer_recipes/sandbox/easyanimate_text_to_video/model_train.yaml
  configs/data_juicer_recipes/sandbox/easyanimate_text_to_video/model_train_2_epoch.yaml
  configs/data_juicer_recipes/sandbox/easyanimate_text_to_video/vbench_eval.yaml
  configs/data_juicer_recipes/sandbox/internvl_coco_caption/all_text_image_stats.yaml
  configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_eval_config.yaml
  configs/data_juicer_recipes/sandbox/internvl_coco_caption/internvl_train_config.yaml
  configs/data_juicer_recipes/sandbox/internvl_coco_caption/sandbox_internvl_coco_caption.yaml
  configs/demo/sandbox/gpt3_extra_train_config.json
  configs/demo/sandbox/gpt3_extra_train_config.yaml
  configs/demo/sandbox/sandbox.yaml
  data_juicer/config/__init__.py
  data_juicer/config/config.py
  data_juicer/core/data/dj_dataset.py
  data_juicer/core/data/load_strategy.py
  data_juicer/core/data/ray_dataset.py
  data_juicer/core/data/schema.py
  data_juicer/core/sandbox/data_pool_manipulators.py
  data_juicer/core/sandbox/env_manager.py
  data_juicer/core/sandbox/evaluators.py
  data_juicer/core/sandbox/factories.py
  data_juicer/core/sandbox/hooks.py
  data_juicer/core/sandbox/model_executors.py
  data_juicer/core/sandbox/pipelines.py
  data_juicer/core/sandbox/specific_hooks/intervl_coco_captioning/model_hooks.py
  data_juicer/core/sandbox/specific_hooks/intervl_coco_captioning/preparation_hooks.py
  data_juicer/core/sandbox/specific_hooks/rft/model_hooks.py
  data_juicer/core/sandbox/specific_hooks/text_to_video/model_hooks.py
  data_juicer/format/formatter.py
  data_juicer/utils/constant.py
  docs/Sandbox.md
  docs/Sandbox_ZH.md
  pyproject.toml
  tests/core/data/test_dj_dataset.py
  tests/core/data/test_ray_dataset.py
  tests/core/data/test_schema.py
  tests/core/sandbox/test_env_manager.py
  thirdparty/models/setup_easyanimate.sh
  tools/hpo/execute_hpo_3sigma.py
  tools/sandbox_starter.py
Labels: enhancement, dj:multimodal, dj:core, environment

#706 CI/CD bugs fixed
  .github/workflows/publish-pypi.yml
  Dockerfile
Labels: dj:ci/cd

#663 Add correlation_analysis in the analysis module
  .github/workflows/unit-test-partial.yml
  data_juicer/analysis/__init__.py
  data_juicer/analysis/correlation_analysis.py
  data_juicer/analysis/draw.py
  data_juicer/core/analyzer.py
  docs/tutorial/QuickStart.md
  docs/tutorial/QuickStart_ZH.md
  tests/analysis/test_correlation_analysis.py
  tests/analysis/test_draw.py
Labels: enhancement, dj:core

#723 Update uv.lock
  pyproject.toml
  uv.lock
Labels: dj:ci/cd, environment
