Repository modelscope/data-juicer, pull requests merged in 2025-03, with the labels that each got.

#604 add unit tests for analysis module
  configs/config_all.yaml
  data_juicer/analysis/column_wise_analysis.py
  data_juicer/analysis/draw.py
  data_juicer/analysis/overall_analysis.py
  data_juicer/config/config.py
  data_juicer/utils/unittest_utils.py
  tests/analysis/test_collector.py
  tests/analysis/test_column_wise_analysis.py
  tests/analysis/test_diversity_analysis.py
  tests/analysis/test_draw.py
  tests/analysis/test_measure.py
  tests/analysis/test_overall_analysis.py
  tests/config/test_config.py
  tests/run.py
  tests/utils/test_unittest_utils.py
Labels: enhancement, dj:ci/cd, dj:core

#606 Add quality and difficulty score filter with LLM APIs
  configs/config_all.yaml
  configs/data_juicer_recipes/data-juicer-sandbox-optimal.yaml
  configs/data_juicer_recipes/data-juicer-sandbox-self-evolution.yaml
  configs/data_juicer_recipes/general-video-refine-example.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/image_nsfw_filter.py
  data_juicer/ops/filter/llm_api_difficulty_score_filter.py
  data_juicer/ops/filter/llm_api_quality_score_filter.py
  data_juicer/ops/filter/video_nsfw_filter.py
  data_juicer/utils/auto_install_mapping.py
  data_juicer/utils/constant.py
  demos/api_service/wrapped_filters.py
  docs/Operators.md
  tests/benchmark_performance/configs/video.yaml
  tests/ops/filter/test_image_nsfw_filter.py
  tests/ops/filter/test_llm_api_difficulty_score_filter.py
  tests/ops/filter/test_llm_api_quality_score_filter.py
  tests/ops/filter/test_video_nsfw_filter.py
  tests/tools/test_process_data.py
Labels: documentation, dj:op, dj:post-tuning

#613 Add API service doc
  README.md
  README_ZH.md
  docs/DJ_service.md
  docs/DJ_service_ZH.md
  environments/minimal_requires.txt
  service.py
  tools/quality_classifier/README.md
  tools/quality_classifier/README_ZH.md
Labels: documentation

#614 quality and difficulty score filter via VLLM
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/llm_difficulty_score_filter.py
  data_juicer/ops/filter/llm_quality_score_filter.py
  data_juicer/utils/auto_install_mapping.py
  docs/Operators.md
  tests/ops/filter/test_llm_difficulty_score_filter.py
  tests/ops/filter/test_llm_quality_score_filter.py
Labels: enhancement, dj:op

#615 update news for MindGYM; minor fix for op naming
  README.md
  README_ZH.md
  tools/quality_classifier/README.md
  tools/quality_classifier/README_ZH.md
Labels: documentation

#618 fix decode error
  data_juicer/utils/constant.py
  tests/run.py
Labels: bug

#627 update to v1.3.0
  README.md
  README_ZH.md
  data_juicer/__init__.py
  docs/DatasetCfg.md
  docs/DatasetCfg_ZH.md
Labels: documentation
