Repository modelscope/data-juicer, pull requests merged in 2025-04, with the labels that each got.

#636 highlight light env install
  README.md
  README_ZH.md
Labels: documentation, environment

#637 Fix boundary issues in other deduplicators
  data_juicer/ops/deduplicator/document_simhash_deduplicator.py
  data_juicer/ops/deduplicator/ray_bts_minhash_deduplicator.py
Labels: bug, dj:op

#634 [NewOp]Mapper to extract tables from HTML content.
  configs/config_all.yaml
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/extract_tables_from_html_mapper.py
  data_juicer/utils/constant.py
  docs/Operators.md
  tests/ops/mapper/test_extract_tables_from_html_mapper.py
Labels: enhancement, dj:op, dj:text

#639 [Update] document_minhash_deduplicator
  data_juicer/ops/deduplicator/document_minhash_deduplicator.py
Labels: enhancement, dj:op, dj:efficiency

#645 Human op enhancement
  configs/annotation/annotation_default.yaml
  configs/annotation/annotation_with_notifications.yaml
  data_juicer/core/data/load_strategy.py
  data_juicer/ops/mapper/annotation/human_preference_annotation_mapper.py
  tests/benchmark_performance/run.sh
  tests/core/data/__init__.py
  tests/ops/mapper/annotation/__init__.py
  tests/ops/mapper/annotation/test_annotation_mapper.py
  tests/ops/mapper/annotation/test_human_preference_annotation_mapper.py
Labels: bug, enhancement, dj:multimodal, dj:op, dj:dataset, dj:post-tuning

#648 fix date typo
  README.md
  README_ZH.md
Labels: bug, documentation

#643 set temp_parser.usage to argparse.SUPPRESS, skip too much help log
  data_juicer/config/config.py
  tests/config/test_config.py
Labels: enhancement

#651 Fix StreamToLoguru compatibility issue with torch._dynamo
  data_juicer/utils/logger_utils.py
Labels: bug, dj:core

#650 Fix docker building failure
  Dockerfile
  environments/science_requires.txt
Labels: bug, dj:ci/cd

#652 add init file for annotation module, fix dj-process command error
  data_juicer/ops/mapper/annotation/__init__.py
Labels: bug

#653 Address possibly missing cfg
  data_juicer/format/formatter.py
Labels: bug

#655 Support hf llm for two llm_xxx_score_filter OPs.
  data_juicer/analysis/column_wise_analysis.py
  data_juicer/ops/filter/llm_difficulty_score_filter.py
  data_juicer/ops/filter/llm_quality_score_filter.py
  docs/Operators.md
Labels: enhancement, dj:op

#657 Sync image to oss
  .github/workflows/publish-docker-oss.yml
  .github/workflows/publish-docker.yml
  Dockerfile
  README.md
  README_ZH.md
Labels: enhancement, dj:ci/cd
