Repository modelscope/data-juicer, pull requests merged in 2025-02, with the labels that each got.

#566 update the 2.0 paper link & the DaaR news
  README.md
  README_ZH.md
Labels: documentation, dj:cookbook, dj:post-tuning

#571 Fix typos
  data_juicer/analysis/draw.py
  data_juicer/config/config.py
  data_juicer/core/tracer.py
  data_juicer/ops/base_op.py
  data_juicer/ops/common/helper_func.py
  data_juicer/ops/deduplicator/ray_bts_minhash_deduplicator.py
  data_juicer/ops/filter/video_motion_score_filter.py
  data_juicer/ops/mapper/pair_preference_mapper.py
  data_juicer/utils/model_utils.py
Labels: documentation

#570 Optimization for sdxl_prompt2prompt_mapper dependency importing
  .github/workflows/deploy_sphinx_docs.yml
  .github/workflows/publish-pypi.yml
  data_juicer/__init__.py
  data_juicer/ops/common/prompt2prompt_pipeline.py
  data_juicer/ops/mapper/sdxl_prompt2prompt_mapper.py
  environments/science_requires.txt
Labels: enhancement, environment

#581 Simplify code logic and improve readability.
  data_juicer/ops/op_fusion.py
Labels: enhancement, dj:op

#589 [OP]Add a new mapper to remove background of images
  configs/config_all.yaml
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/image_remove_background_mapper.py
  data_juicer/utils/auto_install_mapping.py
  docs/Operators.md
  tests/ops/mapper/test_image_remove_background_mapper.py
Labels: enhancement, dj:op

#586 Minor opts for CI/CD
  .github/workflows/deploy_sphinx_docs.yml
  .github/workflows/unit-test.yml
  data_juicer/ops/deduplicator/__init__.py
  data_juicer/ops/mapper/image_remove_background_mapper.py
  data_juicer/utils/unittest_utils.py
  docs/Operators.md
  environments/minimal_requires.txt
  environments/science_requires.txt
  tests/core/test_adapter.py
  tests/core/test_monitor.py
  tests/ops/filter/test_character_repetition_filter.py
  tests/ops/filter/test_image_text_matching_filter.py
  tests/ops/filter/test_video_nsfw_filter.py
  tests/ops/filter/test_video_watermark_filter.py
  tests/ops/mapper/test_generate_qa_from_examples_mapper.py
  tests/ops/mapper/test_generate_qa_from_text_mapper.py
  tests/ops/mapper/test_image_remove_background_mapper.py
  tests/ops/mapper/test_nlpcda_zh_mapper.py
  tests/ops/mapper/test_optimize_qa_mapper.py
  tests/ops/mapper/test_optimize_query_mapper.py
  tests/ops/mapper/test_optimize_response_mapper.py
  tests/ops/mapper/test_query_intent_detection_mapper.py
  tests/ops/mapper/test_query_sentiment_detection_mapper.py
  tests/ops/mapper/test_query_topic_detection_mapper.py
  tests/ops/mapper/test_video_captioning_from_summarizer_mapper.py
  tests/ops/mapper/test_video_remove_watermark_mapper.py
  tests/run.py
Labels: enhancement, dj:ci/cd, environment

#590 fix: image_nsfw_filter.py memory leak. disable gradient
  data_juicer/ops/filter/image_nsfw_filter.py
Labels: dj:op, dj:efficiency

#591 Fix typos
  Dockerfile
  README.md
  README_ZH.md
  app.py
  configs/demo/bench/1_single_op_pipeline.yaml
  configs/demo/bench/2_multi_op_pipeline.yaml
  configs/demo/bench/3_duplicate_pipeline.yaml
  data_juicer/utils/constant.py
  docs/Sandbox-ZH.md
  docs/Sandbox.md
Labels: bug, documentation

#594 Fix logger
  data_juicer/ops/deduplicator/__init__.py
  data_juicer/utils/logger_utils.py
  data_juicer/utils/model_utils.py
  environments/dist_requires.txt
  environments/minimal_requires.txt
Labels: bug, environment

#599 update news for CVPR'25, and official integration by Ray & Arrow
  README.md
  README_ZH.md
Labels: documentation

#593 Fix typos
  data_juicer/ops/mapper/video_captioning_from_audio_mapper.py
  docs/DJ_SORA.md
  docs/DeveloperGuide.md
  tests/ops/grouper/test_naive_reverse_grouper.py
  tests/ops/mapper/test_clean_copyright_mapper.py
  tools/fmt_conversion/multimodal/absolute_path_to_relative_path.py
Labels: documentation
