Repository modelscope/data-juicer, pull requests merged in 2025-01, with the labels that each got.

#518 Dev/manage meta
  configs/config_all.yaml
  data_juicer/ops/aggregator/entity_attribute_aggregator.py
  data_juicer/ops/aggregator/most_relavant_entities_aggregator.py
  data_juicer/ops/aggregator/nested_aggregator.py
  data_juicer/ops/base_op.py
  data_juicer/ops/filter/video_tagging_from_frames_filter.py
  data_juicer/ops/grouper/naive_reverse_grouper.py
  data_juicer/ops/mapper/dialog_intent_detection_mapper.py
  data_juicer/ops/mapper/dialog_sentiment_detection_mapper.py
  data_juicer/ops/mapper/dialog_sentiment_intensity_mapper.py
  data_juicer/ops/mapper/dialog_topic_detection_mapper.py
  data_juicer/ops/mapper/extract_entity_attribute_mapper.py
  data_juicer/ops/mapper/extract_entity_relation_mapper.py
  data_juicer/ops/mapper/extract_event_mapper.py
  data_juicer/ops/mapper/extract_keyword_mapper.py
  data_juicer/ops/mapper/extract_nickname_mapper.py
  data_juicer/ops/mapper/extract_support_text_mapper.py
  data_juicer/ops/mapper/image_tagging_mapper.py
  data_juicer/ops/mapper/query_intent_detection_mapper.py
  data_juicer/ops/mapper/query_sentiment_detection_mapper.py
  data_juicer/ops/mapper/query_topic_detection_mapper.py
  data_juicer/ops/mapper/relation_identity_mapper.py
  data_juicer/ops/mapper/video_captioning_from_summarizer_mapper.py
  data_juicer/ops/mapper/video_extract_frames_mapper.py
  data_juicer/ops/mapper/video_tagging_from_audio_mapper.py
  data_juicer/ops/mapper/video_tagging_from_frames_mapper.py
  data_juicer/utils/common_utils.py
  data_juicer/utils/constant.py
  data_juicer/utils/file_utils.py
  data_juicer/utils/model_utils.py
  demos/role_playing_system_prompt/role_playing_system_prompt.yaml
  demos/role_playing_system_prompt/system_prompt_generator.py
  tests/ops/aggregator/test_entity_attribute_aggregator.py
  tests/ops/aggregator/test_most_relavant_entities_aggregator.py
  tests/ops/aggregator/test_nested_aggregator.py
  tests/ops/grouper/test_naive_reverse_grouper.py
  tests/ops/mapper/test_dialog_intent_detection_mapper.py
  tests/ops/mapper/test_dialog_sentiment_detection_mapper.py
  tests/ops/mapper/test_dialog_sentiment_intensity_mapper.py
  tests/ops/mapper/test_dialog_topic_detection_mapper.py
  tests/ops/mapper/test_extract_entity_attribute_mapper.py
  tests/ops/mapper/test_extract_entity_relation_mapper.py
  tests/ops/mapper/test_extract_event_mapper.py
  tests/ops/mapper/test_extract_keyword_mapper.py
  tests/ops/mapper/test_extract_nickname_mapper.py
  tests/ops/mapper/test_extract_support_text_mapper.py
  tests/ops/mapper/test_image_tagging_mapper.py
  tests/ops/mapper/test_query_intent_detection_mapper.py
  tests/ops/mapper/test_query_sentiment_detection_mapper.py
  tests/ops/mapper/test_query_topic_detection_mapper.py
  tests/ops/mapper/test_relation_identity_mapper.py
  tests/ops/mapper/test_video_extract_frames_mapper.py
  tests/ops/mapper/test_video_tagging_from_audio_mapper.py
  tests/ops/mapper/test_video_tagging_from_frames_mapper.py
Labels: enhancement, dj:dataset, dj:core

#529 fix force download bug
  data_juicer/utils/model_utils.py
Labels: bug, dj:core

#530 Remove sandbox requirements installation from Dockerfile
  Dockerfile
Labels: dj:ci/cd, environment

#523 docs for distributed processing
  demos/process_on_ray/configs/dedup.yaml
  demos/process_on_ray/configs/demo.yaml
  docs/Distributed.md
  docs/Distributed_ZH.md
Labels: documentation, dj:dist

#532 [Hot Fix] Update Ray version
  data_juicer/core/ray_data.py
  environments/dist_requires.txt
Labels: environment

#538 fix missing field meta tag on ray mode
  data_juicer/core/ray_data.py
Labels: bug

#543 update a quick cdn link for arch figure
  README.md
  README_ZH.md
  docs/Distributed.md
  docs/Distributed_ZH.md
Labels: documentation

#541 limit the generated qa num for each text in generate_qa_from_text_mapper
  configs/config_all.yaml
  data_juicer/ops/mapper/generate_qa_from_text_mapper.py
  tests/ops/mapper/test_generate_qa_from_text_mapper.py
Labels: enhancement, dj:op

#536 fix save_ckpt bug
  data_juicer/utils/ckpt_utils.py
Labels: bug, dj:core

#527 [Feature] Auto generation for OP docs
  .pre-commit-config.yaml
  .pre-commit-hooks/build_op_doc.py
  .pre-commit-hooks/tag_mappings.json
  README.md
  README_ZH.md
  docs/DJ_SORA.md
  docs/DJ_SORA_ZH.md
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  docs/Operators.md
  docs/Operators_ZH.md
  tests/ops/selector/test_tags_specified_field_selector.py
Labels: documentation, enhancement, dj:ci/cd

#544 Bug fixed: generating too short texts and no valid QA is extracted.
  data_juicer/ops/mapper/generate_qa_from_examples_mapper.py
  data_juicer/ops/mapper/generate_qa_from_text_mapper.py
  data_juicer/ops/mapper/optimize_qa_mapper.py
  data_juicer/utils/model_utils.py
Labels: bug, dj:op

#550 Add Img-Diff ops.
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/text_pair_similarity_filter.py
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/image_segment_mapper.py
  data_juicer/ops/mapper/mllm_mapper.py
  data_juicer/ops/mapper/sdxl_prompt2prompt_mapper.py
  data_juicer/ops/mapper/sentence_augmentation_mapper.py
  data_juicer/utils/constant.py
  data_juicer/utils/model_utils.py
  docs/Operators.md
  environments/science_requires.txt
  tests/ops/filter/test_text_pair_similarity_filter.py
  tests/ops/mapper/test_dialog_intent_detection_mapper.py
  tests/ops/mapper/test_image_segment_mapper.py
  tests/ops/mapper/test_mllm_mapper.py
  tests/ops/mapper/test_sdxl_prompt2prompt_mapper.py
  tests/ops/mapper/test_sentence_augmentation_mapper.py
Labels: enhancement, dj:multimodal, dj:op

#552 optimize op doc for global textual search; correct beta into stable
  .pre-commit-hooks/build_op_doc.py
  .pre-commit-hooks/tag_mappings.json
  README.md
  README_ZH.md
  docs/Operators.md
Labels: documentation, dj:op

#528 Refine/llm api op unittest
  configs/config_all.yaml
  data_juicer/config/config.py
  data_juicer/ops/base_op.py
  tests/config/test_config_funcs.py
  tests/ops/aggregator/test_entity_attribute_aggregator.py
  tests/ops/aggregator/test_most_relavant_entities_aggregator.py
  tests/ops/aggregator/test_nested_aggregator.py
  tests/ops/mapper/test_dialog_intent_detection_mapper.py
  tests/ops/mapper/test_dialog_sentiment_detection_mapper.py
  tests/ops/mapper/test_dialog_sentiment_intensity_mapper.py
  tests/ops/mapper/test_dialog_topic_detection_mapper.py
  tests/ops/mapper/test_extract_entity_attribute_mapper.py
  tests/ops/mapper/test_extract_entity_relation_mapper.py
  tests/ops/mapper/test_extract_event_mapper.py
  tests/ops/mapper/test_extract_keyword_mapper.py
  tests/ops/mapper/test_extract_nickname_mapper.py
  tests/ops/mapper/test_extract_support_text_mapper.py
  tests/ops/mapper/test_relation_identity_mapper.py
Labels: enhancement, dj:core

#557 fix export error when export_stats columns is null
  data_juicer/core/exporter.py
Labels: bug, dj:core

#561 Refactor and improve doc for RecipeGallery, DeveloperGuide, DistributedProcess and DJ-related Competitions
  README.md
  README_ZH.md
  configs/README.md
  configs/README_ZH.md
  configs/data_juicer_recipes/README.md
  configs/data_juicer_recipes/README_ZH.md
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ZH.md
  docs/Distributed.md
  docs/Distributed_ZH.md
  docs/RecipeGallery.md
  docs/RecipeGallery_ZH.md
Labels: documentation, enhancement, dj:cookbook

#562 fix translation error
  README.md
  docs/RecipeGallery.md
Labels: documentation
