Repository modelscope/data-juicer, pull requests merged in 2025-07, with the labels that each got.

#720 add subprocess coverage support and some unittests
  .coveragerc
  .github/workflows/unit-test-partial.yml
  .github/workflows/unit-test.yml
  .secrets.baseline
  data_juicer/ops/mapper/image_captioning_from_gpt4v_mapper.py
  docs/Operators.md
  tests/ops/deduplicator/test_document_deduplicator.py
  tests/ops/deduplicator/test_document_simhash_deduplicator.py
  tests/ops/deduplicator/test_image_deduplicator.py
  tests/ops/deduplicator/test_video_deduplicator.py
  tests/ops/mapper/annotation/test_annotation_mapper.py
  tests/ops/mapper/annotation/test_human_preference_annotation_mapper.py
  tests/ops/mapper/test_generate_qa_from_examples_mapper.py
  tests/ops/mapper/test_generate_qa_from_text_mapper.py
  tests/ops/mapper/test_image_captioning_from_gpt4v_mapper.py
  tests/ops/mapper/test_optimize_qa_mapper.py
  tests/ops/mapper/test_optimize_query_mapper.py
  tests/ops/mapper/test_optimize_response_mapper.py
  tests/run.py
Labels: dj:op

#730 [bug fix] Fix bug for issue #711: the parameters will be overwritten by the same operator
  data_juicer/config/config.py
Labels: bug, dj:core

#725 Support store image bytes in the dataset
  configs/config_all.yaml
  data_juicer/config/config.py
  data_juicer/core/analyzer.py
  data_juicer/core/data/ray_dataset.py
  data_juicer/core/executor/default_executor.py
  data_juicer/core/executor/ray_executor.py
  data_juicer/core/exporter.py
  data_juicer/core/ray_exporter.py
  data_juicer/ops/base_op.py
  data_juicer/ops/deduplicator/image_deduplicator.py
  data_juicer/ops/deduplicator/ray_image_deduplicator.py
  data_juicer/ops/filter/image_aesthetics_filter.py
  data_juicer/ops/filter/image_aspect_ratio_filter.py
  data_juicer/ops/filter/image_face_count_filter.py
  data_juicer/ops/filter/image_face_ratio_filter.py
  data_juicer/ops/filter/image_nsfw_filter.py
  data_juicer/ops/filter/image_pair_similarity_filter.py
  data_juicer/ops/filter/image_shape_filter.py
  data_juicer/ops/filter/image_size_filter.py
  data_juicer/ops/filter/image_text_matching_filter.py
  data_juicer/ops/filter/image_text_similarity_filter.py
  data_juicer/ops/filter/image_watermark_filter.py
  data_juicer/ops/filter/phrase_grounding_recall_filter.py
  data_juicer/ops/mapper/download_file_mapper.py
  data_juicer/ops/mapper/image_blur_mapper.py
  data_juicer/ops/mapper/image_diffusion_mapper.py
  data_juicer/ops/mapper/image_face_blur_mapper.py
  data_juicer/ops/mapper/image_remove_background_mapper.py
  data_juicer/ops/mapper/image_segment_mapper.py
  data_juicer/ops/mapper/image_tagging_mapper.py
  data_juicer/ops/op_fusion.py
  data_juicer/utils/common_utils.py
  data_juicer/utils/file_utils.py
  data_juicer/utils/mm_utils.py
  data_juicer/utils/webdataset_utils.py
  demos/data/demo-dataset-images-bytes.parquet
  docs/Operators.md
  tests/config/test_config.py
  tests/core/test_ray_exporter.py
  tests/ops/mapper/test_download_file_mapper.py
  tests/tools/test_process_data.py
  tests/utils/test_file_utils.py
Labels: enhancement, dj:multimodal, dj:dist, dj:core

#746 docs: add Sphinx video link transforms; refresh README; expose all releases ≥ v1.4.0 in multi-version docs
  README.md
  README_ZH.md
  docs/sphinx_doc/source/conf.py
  docs/sphinx_doc/source/custom_myst.py
Labels: documentation
