Repository modelscope/data-juicer, pull requests merged in 2025-05, with the labels that each got.

#659 improve clarity & bad links fix
  docs/DatasetCfg.md
  docs/DatasetCfg_ZH.md
  tools/fmt_conversion/README.md
  tools/fmt_conversion/README_ZH.md
Labels: documentation, dj:cookbook

#662 Docs updating
  README.md
  README_ZH.md
  tools/fmt_conversion/post_tuning_dialog/README.md
  tools/fmt_conversion/post_tuning_dialog/README_ZH.md
Labels: documentation

#658 Add Img-Diff recipes.
  configs/config_all.yaml
  configs/data_juicer_recipes/img-diff-recipe.yaml
  data_juicer/ops/base_op.py
  data_juicer/ops/filter/image_pair_similarity_filter.py
  data_juicer/ops/mapper/__init__.py
  data_juicer/ops/mapper/imgdiff_difference_area_generator_mapper.py
  data_juicer/ops/mapper/imgdiff_difference_caption_generator_mapper.py
  data_juicer/ops/mapper/sdxl_prompt2prompt_mapper.py
  data_juicer/ops/mapper/sentence_augmentation_mapper.py
  data_juicer/utils/file_utils.py
  data_juicer/utils/logger_utils.py
  data_juicer/utils/model_utils.py
  docs/Operators.md
  environments/science_requires.txt
  setup.cfg
  tests/ops/data/img_pair_1.jpg
  tests/ops/data/img_pair_2.jpg
  tests/ops/mapper/test_imgdiff_difference_area_generator_mapper.py
  tests/ops/mapper/test_imgdiff_difference_caption_generator_mapper.py
  tests/ops/mapper/test_sdxl_prompt2prompt_mapper.py
  tests/ops/mapper/test_sentence_augmentation_mapper.py
  tests/utils/test_logger_utils.py
Labels: enhancement, dj:multimodal, dj:op

#666 Split standalone and dist unit tests into different jobs
  .github/workflows/unit-test-partial.yml
  .github/workflows/unit-test.yml
  .secrets.baseline
Labels: dj:ci/cd

#673 [NewOp]Add a new filter - general_field_filter
  configs/config_all.yaml
  data_juicer/ops/filter/__init__.py
  data_juicer/ops/filter/general_field_filter.py
  data_juicer/utils/constant.py
  docs/Operators.md
  tests/ops/filter/test_general_field_filter.py
Labels: enhancement, dj:op

#668 Ignore the installed distutils libs for docker image building
  .github/workflows/publish-docker.yml
  Dockerfile
Labels: bug, dj:ci/cd

#644 Adds gpu minhash support for RayBTSMinhashDeduplicator
  data_juicer/ops/deduplicator/ray_bts_minhash_deduplicator.py
Labels: enhancement, dj:op, dj:efficiency
